package vista;

import clasesDeApoyo.Conexion;
import controlador.ParqueaderoControlador;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import modelo.Convenio;
import modelo.Parqueadero;
import modelo.Tarifa;
import controlador.VehiculoControlador;
import modelo.Vehiculo;
import org.apache.log4j.Logger;


/**
 *
 * @author ALEJO
 */
public class EditarVehiculo extends javax.swing.JFrame {

    String vehiculo_actualizado="";
    String propietariaBack;
    int noParqueaderoBack;
    String claseBack;
    int convenioBack;
    int tarifaBack;
    
    boolean elVehiculoTieneFacturas = false;
    boolean elVehiculoEstaEnParqueadero = false;
    
    int ID;
    javax.swing.JTable tablaVehi;
    int FilaAnterior;
    DefaultTableModel modelo;
    int seleccionParq;
    
    Convenio conv = new Convenio();
    Tarifa tarif = new Tarifa();
    Parqueadero parq = new Parqueadero();
    
    Parqueadero nomParq;
    Convenio nomConvenio;
    Tarifa nomTarifa;  
    Vehiculo vehiculoConsultado = new Vehiculo(0, "", "", "", 0, 0, 0);
    
    VehiculoControlador vehicontrolador = new VehiculoControlador();
    ParqueaderoControlador parqControla = new ParqueaderoControlador();
      
    private final Logger log = Logger.getLogger(EditarVehiculo.class);
    private URL url = EditarVehiculo.class.getResource("Log4j.properties");
    
    /**
     * Creates new form nuevoUsuario
     */
    public EditarVehiculo() {
        initComponents();
        vehiculo_actualizado = PanelVehiculos.vehiculo_update;
        tablaVehi = PanelVehiculos.Table_listaVehiculos;
        modelo = PanelVehiculos.modelo;
        
        setSize(630,375);
        setResizable(false);
        setTitle("Editar vehiculo");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DO_NOTHING_ON_CLOSE);
        
        DefaultComboBoxModel modeloParq = new DefaultComboBoxModel(parq.mostrarParqueaderos());
        cmb_noParqueadero.setModel(modeloParq);
        
        DefaultComboBoxModel modeloConv = new DefaultComboBoxModel(conv.mostrarConveniosDisponibles());
        cmb_convenios.setModel(modeloConv);

        DefaultComboBoxModel modeloTarif = new DefaultComboBoxModel(tarif.mostrarTarifasDisponibles());
        cmb_tarifas.setModel(modeloTarif);
        
        //Traemos el objeto tipo vehiculo con la info del vehiculo a editar
        vehiculoConsultado = vehicontrolador.consultarInformacionDeUnVehiculo(vehiculo_actualizado);
         
        //Colocamos la infromacion del objeto vehiculo en la interfaz
        ID = vehiculoConsultado.getId();
        txt_placa.setText(vehiculoConsultado.getPlaca());
        
        propietariaBack = vehiculoConsultado.getPropietario();
        txt_dueño.setText(propietariaBack);

        claseBack = vehiculoConsultado.getClase();
        cmb_clase.setSelectedItem(claseBack);

        noParqueaderoBack = vehiculoConsultado.getId_parqueadero();
        cmb_noParqueadero.setSelectedIndex(noParqueaderoBack);

        convenioBack = vehiculoConsultado.getId_convenio();
        cmb_convenios.setSelectedIndex(convenioBack);

        tarifaBack = vehiculoConsultado.getId_tarifa();
        cmb_tarifas.setSelectedIndex(tarifaBack);

        aparienciaTipoVehiculo();
        elVehiculoEstaEnParqueadero = vehicontrolador.verificarSiVehiculoEstaEnParqueadero(vehiculo_actualizado);
        elVehiculoTieneFacturas = vehicontrolador.consultarSiVehiculoTieneFacturas(vehiculo_actualizado);
        parqControla.liberarParqueadero(vehiculo_actualizado);
        vehicontrolador.liberarVehiculo(ID);
            
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("icons/IcoCar.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txt_placa = new javax.swing.JTextField();
        txt_dueño = new javax.swing.JTextField();
        btn_cancelar = new javax.swing.JButton();
        btn_actualizar = new javax.swing.JButton();
        lbl_imgEditUsuario = new javax.swing.JLabel();
        cmb_noParqueadero = new javax.swing.JComboBox<>();
        cmb_convenios = new javax.swing.JComboBox<>();
        cmb_tarifas = new javax.swing.JComboBox<>();
        cmb_clase = new javax.swing.JComboBox<>();
        check_editEstaVehiculoEnParqueadero = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconImage(getIconImage());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Placa:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Propietario:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Clase:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("N° de parqueadero:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Convenio:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Tarifa:");

        txt_placa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_placaKeyTyped(evt);
            }
        });

        txt_dueño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_dueñoKeyTyped(evt);
            }
        });

        btn_cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Cancelar.png"))); // NOI18N
        btn_cancelar.setText("Cancelar");
        btn_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelarActionPerformed(evt);
            }
        });

        btn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh256_24854.png"))); // NOI18N
        btn_actualizar.setText("Actualizar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });

        lbl_imgEditUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_imgEditUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/EditCar.png"))); // NOI18N

        cmb_noParqueadero.setAutoscrolls(true);
        cmb_noParqueadero.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_noParqueaderoItemStateChanged(evt);
            }
        });

        cmb_convenios.setAutoscrolls(true);
        cmb_convenios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_conveniosItemStateChanged(evt);
            }
        });

        cmb_tarifas.setAutoscrolls(true);

        cmb_clase.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "AUTOMOVIL", "MOTO" }));
        cmb_clase.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_claseItemStateChanged(evt);
            }
        });

        check_editEstaVehiculoEnParqueadero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        check_editEstaVehiculoEnParqueadero.setText("Está en parqueadero");
        check_editEstaVehiculoEnParqueadero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_editEstaVehiculoEnParqueaderoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_dueño, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_clase, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_noParqueadero, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cmb_convenios, javax.swing.GroupLayout.Alignment.LEADING, 0, 163, Short.MAX_VALUE)
                                .addComponent(cmb_tarifas, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                        .addComponent(lbl_imgEditUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txt_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(check_editEstaVehiculoEnParqueadero)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_actualizar)
                .addGap(18, 18, 18)
                .addComponent(btn_cancelar)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel1)
                            .addComponent(txt_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(check_editEstaVehiculoEnParqueadero)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(lbl_imgEditUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel2)
                            .addComponent(txt_dueño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel3)
                            .addComponent(cmb_clase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel4)
                            .addComponent(cmb_noParqueadero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel5)
                            .addComponent(cmb_convenios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel6)
                            .addComponent(cmb_tarifas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_actualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Metodo del boton cancelar
    private void btn_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelarActionPerformed
        ocuparParqueadero(vehiculo_actualizado, propietariaBack, noParqueaderoBack);
        recargarVehiculo();
        PanelVehiculos.hayVehiculoEnEdicion = false;
        dispose();    
    }//GEN-LAST:event_btn_cancelarActionPerformed

    //Metodo boton Actualizar
    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
       
        int tipVehi_cmb, validacion = 0;
        String placa, dueño = "";
        String tipoVehi_string="";
        
        placa = txt_placa.getText().trim();
        dueño = txt_dueño.getText().trim();
      
        tipVehi_cmb = cmb_clase.getSelectedIndex() + 1;
       
        
        //Creamos un objeto de la clase modelo Convenio con lo seleccionado en el combobox de Convenio
        nomConvenio = (Convenio)cmb_convenios.getSelectedItem(); 
        
        //Creamos un objeto de la clase modelo Tarifa con lo seleccionado en el combobox de Tarifas
        nomTarifa = (Tarifa)cmb_tarifas.getSelectedItem(); 
        
        //Creamos un objeto de la clase modelo Parqueadero con lo seleccionado en el combobox de Parq
        nomParq = (Parqueadero)cmb_noParqueadero.getSelectedItem(); 
        
        
        int convenioValido = nomConvenio.getId();
        int tarifaValida = nomTarifa.getId();
        int parqValido = nomParq.getId();
        
        
        if(placa.equals("")){
            txt_placa.setBackground(Color.red);
            validacion++;
        }
        if(dueño.equals("")){
            txt_dueño.setBackground(Color.red);
            validacion++;
        }
        
        if(tipVehi_cmb == 1){
            tipoVehi_string = "Seleccione"; 
            validacion++;
        }        
        else if(tipVehi_cmb == 2){
            tipoVehi_string = "AUTOMOVIL";
        }else if(tipVehi_cmb == 3){
            tipoVehi_string = "MOTO";
        } 
        
        if(parqValido==0){
            cmb_noParqueadero.setBackground(Color.red);
            validacion++;
        }
        
        if(convenioValido==0){
            cmb_convenios.setBackground(Color.red);
            validacion++;
        }
        
        if(tarifaValida==0){
            cmb_tarifas.setBackground(Color.red);
            validacion++;
        }
        
        //Valida que el vehiculo ingresado no exista previamente en la BD  
        try {
            Connection cn = Conexion.conectar();
            PreparedStatement pst;
            pst = cn.prepareStatement(
                        "select Placa from vehiculos where Placa = '" + placa + "'");
            
            ResultSet rs = pst.executeQuery();
            
            if (rs.next()) {
                txt_placa.setBackground(Color.red);
                JOptionPane.showMessageDialog(null, "El vehiculo ya se encuentra registrado.");
                cn.close();
                txt_placa.setText(vehiculo_actualizado);
                Normalizar();
            } else {           
               
                //Valida que el parqueadero indicado no se encuentre ocupado
                try {
                    Connection cn5 = Conexion.conectar();
                    PreparedStatement pst5;
                    pst5 = cn5.prepareStatement(
                                "select Nombre_parqueadero, Estado from parqueaderos where Nombre_parqueadero = '" + nomParq.getNombre() + "' AND Estado='Ocupado'");
            
                    ResultSet rs5 = pst5.executeQuery();
            
                    if (rs5.next()) {
                        cmb_noParqueadero.setBackground(Color.red);
                        JOptionPane.showMessageDialog(null, "El parqueadero indicado se encuentra ocupado.");
                        cn5.close();
                        Normalizar();
                    } else {              

                        if (validacion == 0) {

                            FilaAnterior = tablaVehi.getSelectedRow();
                
                            try{
                                Connection c8 = Conexion.conectar();
                                PreparedStatement pst8 = c8.prepareStatement("update vehiculos set Placa ='"+placa+"',Propietario='"+dueño+"',Clase='"+tipoVehi_string+"',Id_parqueadero="+nomParq.getId()+",Id_convenio="+nomConvenio.getId()+",Id_tarifa="+nomTarifa.getId()+" where Placa ='000000'");

                                pst8.executeUpdate();
                                c8.close();

                                Object Fila[] = new Object[6];
                                Fila[0] = placa;
                                Fila[1] = dueño;
                                Fila[2] = tipoVehi_string;
                                Fila[3] = nomParq.getNombre();
                                Fila[4] = nomConvenio.getNombre();
                                Fila[5] = nomTarifa.getNombreTarifa();

                                modelo.addRow(Fila);
                                modelo.removeRow(FilaAnterior);
                                
                                //Actualizamos el parqueadero de Disponible a Ocupado
                                ocuparParqueadero(placa, dueño, nomParq.getId());
                                
                                //Actualizamos las facturas con la info nueva
                                actualizarFacturas(placa, dueño, tipoVehi_string, nomParq.getId(), nomConvenio.getId(), nomTarifa.getId());
                                
                                JOptionPane.showMessageDialog(null, "Vehiculo actualizado satisfactoriamente");
                                PanelVehiculos.hayVehiculoEnEdicion = false;
                                dispose();
                                                               
                            }catch(SQLException e){
                                JOptionPane.showMessageDialog(null, "¡¡ERROR al actualizar!!, contacte al administrador.");
                            }    
                            
                        } else {
                            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos.");
                            Normalizar();
                        }               
                    }    
                } catch (SQLException ex) {
                   JOptionPane.showMessageDialog(null, "¡¡ERROR al revisar cupo!!, contacte al administrador.");
                }
            }
        } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "¡¡ERROR al revisar existencia de vehiculo, contacte al administrador.");
        }
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void txt_placaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_placaKeyTyped
        
        //Cuenta la cantidad maxima de caracteres
        int numeroCaracteres = 5;
        if(txt_placa.getText().length()== numeroCaracteres){
            evt.consume();
            JOptionPane.showMessageDialog(null,"Solo 6 caracteres");
        }

        ///Forza a escribir en mayuscula
        char c=evt.getKeyChar();
        if(Character.isLowerCase(c)){
            evt.setKeyChar(Character.toUpperCase(c));
            
        }
    }//GEN-LAST:event_txt_placaKeyTyped

    private void txt_dueñoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_dueñoKeyTyped
        //Cuenta la cantidad maxima de caracteres
        int numeroCaracteres = 30;
        if(txt_dueño.getText().length()== numeroCaracteres){
            evt.consume();
            JOptionPane.showMessageDialog(null,"Solo 30 caracteres");
        }


        ////Forza a escribir en mayuscula
        char c=evt.getKeyChar();
        if(Character.isLowerCase(c)){
            evt.setKeyChar(Character.toUpperCase(c));
            
        }
    }//GEN-LAST:event_txt_dueñoKeyTyped

    private void cmb_noParqueaderoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_noParqueaderoItemStateChanged
        
    }//GEN-LAST:event_cmb_noParqueaderoItemStateChanged

    private void cmb_claseItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_claseItemStateChanged
        aparienciaTipoVehiculo();
    }//GEN-LAST:event_cmb_claseItemStateChanged

    private void cmb_conveniosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_conveniosItemStateChanged
       aparienciaConvenio();
    }//GEN-LAST:event_cmb_conveniosItemStateChanged

    private void check_editEstaVehiculoEnParqueaderoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_editEstaVehiculoEnParqueaderoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_check_editEstaVehiculoEnParqueaderoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarVehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    //Esto cambia la apariencia de la app para que se acomode al Siste Operativo
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    new EditarVehiculo().setVisible(true);
                }   catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    //Logger.getLogger(EditarVehiculo.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_cancelar;
    private javax.swing.JCheckBox check_editEstaVehiculoEnParqueadero;
    private javax.swing.JComboBox<String> cmb_clase;
    private javax.swing.JComboBox<String> cmb_convenios;
    private javax.swing.JComboBox<String> cmb_noParqueadero;
    private javax.swing.JComboBox<String> cmb_tarifas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel lbl_imgEditUsuario;
    private javax.swing.JTextField txt_dueño;
    private javax.swing.JTextField txt_placa;
    // End of variables declaration//GEN-END:variables

    //Metodo que limpia el formulario
    public void Limpiar(){
        txt_placa.setText("");
        txt_dueño.setText("");
        cmb_clase.setSelectedIndex(0);
        cmb_noParqueadero.setSelectedIndex(0);
        cmb_convenios.setSelectedIndex(0);
        cmb_tarifas.setSelectedIndex(0);
    }
    
    //Metodo que normaliza el formulario
    public void Normalizar(){
        txt_placa.setBackground(Color.WHITE);
        txt_dueño.setBackground(Color.WHITE);
        cmb_clase.setBackground(Color.WHITE);
        cmb_noParqueadero.setBackground(Color.WHITE);
        cmb_convenios.setBackground(Color.WHITE);
        cmb_tarifas.setBackground(Color.WHITE);
    }
    
    //Pasa el parqueadero seleccionado de disponible a ocupado
    public void ocuparParqueadero(String placaV, String dueñoV, int ParqueaderoV){
                 
//        if(ParqueaderoV == noParqueaderoBack){
//            
////            if(vehiculoEstabaEnParquadero == true){
////            //Actualizamos el estado del parqueadero seleccionado de Disponible a Ocupado 
////            try{
////                Connection cn3 = Conexion.conectar();
////                PreparedStatement pst3 = cn3.prepareStatement("update parqueaderos set Estado ='Ocupado', Placa='"+placaV+"',Propietario='"+dueñoV+"',Esta_en_parqueadero='Si' where Id_parqueadero ='"+ParqueaderoV+"'");
////
////                pst3.executeUpdate();
////                cn3.close();
////
////            }catch(SQLException e){
////                JOptionPane.showMessageDialog(null, "¡¡ERROR al actualizar!!, contacte al administrador.");
////                Limpiar();
////            }
////            
////            }else if(vehiculoEstabaEnParquadero == false){
////                //Actualizamos el estado del parqueadero seleccionado de Disponible a Ocupado 
////                try{
////                    Connection cn3 = Conexion.conectar();
////                    PreparedStatement pst3 = cn3.prepareStatement("update parqueaderos set Estado ='Ocupado', Placa='"+placaV+"',Propietario='"+dueñoV+"',Esta_en_parqueadero='No' where Id_parqueadero ='"+ParqueaderoV+"'");
////
////                    pst3.executeUpdate();
////                    cn3.close();
////
////                }catch(SQLException e){
////                    JOptionPane.showMessageDialog(null, "¡¡ERROR al actualizar!!, contacte al administrador.");
////                    Limpiar();
////                }
////            }        
//        }else{
//            if(vehiculoEstabaEnParquadero == true){
//            //Actualizamos el estado del parqueadero seleccionado de Disponible a Ocupado 
//            try{
//                Connection cn3 = Conexion.conectar();
//                PreparedStatement pst3 = cn3.prepareStatement("update parqueaderos set Estado ='Ocupado', Placa='"+placaV+"',Propietario='"+dueñoV+"',Esta_en_parqueadero='Si' where Id_parqueadero ='"+ParqueaderoV+"'");
//
//                pst3.executeUpdate();
//                cn3.close();
//
//            }catch(SQLException e){
//                JOptionPane.showMessageDialog(null, "¡¡ERROR al actualizar!!, contacte al administrador.");
//                Limpiar();
//            }
//            
//            }else if(vehiculoEstabaEnParquadero == false){
//                //Actualizamos el estado del parqueadero seleccionado de Disponible a Ocupado 
//                try{
//                    Connection cn3 = Conexion.conectar();
//                    PreparedStatement pst3 = cn3.prepareStatement("update parqueaderos set Estado ='Ocupado', Placa='"+placaV+"',Propietario='"+dueñoV+"',Esta_en_parqueadero='No' where Id_parqueadero ='"+ParqueaderoV+"'");
//
//                    pst3.executeUpdate();
//                    cn3.close();
//
//                }catch(SQLException e){
//                    JOptionPane.showMessageDialog(null, "¡¡ERROR al actualizar!!, contacte al administrador.");
//                    Limpiar();
//                }
//            } 
//        }
    }
    
       
    //Metodo que define la apariencia del formulario con respecto al campo clase
    public void aparienciaTipoVehiculo(){
        String tipVehi_string = (String)cmb_clase.getSelectedItem();
            
        if(tipVehi_string.equals("Seleccione")){
            cmb_convenios.setSelectedIndex(0);
            cmb_tarifas.setSelectedIndex(0);

        } else if(tipVehi_string.equals("AUTOMOVIL")){
            cmb_convenios.setSelectedIndex(1);
            cmb_tarifas.setSelectedIndex(2);

        } else if(tipVehi_string.equals("MOTO")){
            cmb_convenios.setSelectedIndex(1);
            cmb_tarifas.setSelectedIndex(3);
        }
    }
    
    //Metodo que define la apariencia del formulario con respecto al campo convenio
    public void aparienciaConvenio(){
        int conv_string = cmb_convenios.getSelectedIndex();
        String tipVehi_string = (String)cmb_clase.getSelectedItem();
        
        if(conv_string == 1){
            if(tipVehi_string.equals("AUTOMOVIL")){
            cmb_tarifas.setSelectedIndex(2);

            } else if(tipVehi_string.equals("MOTO")){
                cmb_tarifas.setSelectedIndex(3);
            }
        }
        
        if(conv_string > 1){
            cmb_tarifas.setSelectedIndex(1);
        } 
    }
    
    //Metodo que recarga el vehiculo
    public void recargarVehiculo(){
        
        try{
            Connection cn9 = Conexion.conectar();
            PreparedStatement pst9 = cn9.prepareStatement("update vehiculos set Placa ='"+vehiculo_actualizado+"' where Id_vehiculo ='"+ID+"'");

            pst9.executeUpdate();
            cn9.close();

        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Error al recargar vehiculo, contacte al administrador.");
        } 
    }
    
    
    
    
 
    
    public void actualizarFacturas(String placa, String dueño, String tipVehi, int IdParq, int IdConv, int IdTarif){
        
        try{
            Connection cn9 = Conexion.conectar();
            PreparedStatement pst9 = cn9.prepareStatement("update facturas set Placa ='"+placa+"', Propietario='"+dueño+"', Tipo_vehiculo='"+tipVehi+"', No_parqueadero='"+IdParq+"', Id_convenio='"+IdConv+"', Id_tarifa='"+IdTarif+"' where Placa ='"+vehiculo_actualizado+"' and Estado_fctra='Abierta'");

            pst9.executeUpdate();
            cn9.close();

        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Error al actualizar facturas, contacte al administrador.");
            System.out.println(e);
        } 
    }
}
