package vista;

import com.sun.glass.events.KeyEvent;
import controlador.FacturaControlador;
import controlador.UsuarioControlador;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import modelo.Usuario;
import org.apache.log4j.Logger;


/**
 *
 * @author ALEJO
 */
public class GestionarFacturas extends javax.swing.JFrame {
         
    public static DefaultTableModel modelo;
    public static int Filas;
    public static String codigoFactura_update;
    
    public static boolean esFacturaAbierta = false;
    public static boolean hayFacturaVisualizandose = false;
    public static int idCierre;
        
    Usuario objUsuarioParaCombobox = new Usuario();
    String totalPorFacturas = "";
    ArrayList valoresAPagarDeFacturas;
    
    FacturaControlador facturaControla = new FacturaControlador();
    UsuarioControlador usuarioControla= new UsuarioControlador();
    
    
    private final Logger log = Logger.getLogger(GestionarFacturas.class);
    private URL url = GestionarFacturas.class.getResource("Log4j.properties");
    
    /**
     * Creates new form nuevoUsuario
     */
    public GestionarFacturas() {       
        initComponents();
        setSize(667, 500);
        setResizable(false);
        setTitle("Gestionar facturas");
        setLocationRelativeTo(null);
        
        //Avisamos que esta ventana se encuentra abierta para que no deje cerrar sesion al usuario
        MenuAdministrador.hayAlgunaVentanaAbiertaDelSistema = true;
        
        //Cargamos los usuarios existentes en el sistema en el combobox
        DefaultComboBoxModel modeloUsuarios = new DefaultComboBoxModel(objUsuarioParaCombobox.listadoUsuariosDelSistema());
        cmb_usuarios.setModel(modeloUsuarios);
                                        
        if(idCierre != 1){
            facturaControla.cargarFacturasDeUnCierre(idCierre);
           
            //Calculamos el totalde ganancias por facturas teniendo en cuenta el codigo de cierre
            //Obtenemos los valores a pagar de las facturas para hacer calculo del total por facturas
            valoresAPagarDeFacturas = facturaControla.obtenerValoresAPagarFacturasBajoAlgunCriterio(" AND Id_cierre = " + Integer.toString(idCierre));
                
            //Calculamos el total por facturas teniendo en cuenta los valores de pagar de las facturas obtenidas
            totalPorFacturas = facturaControla.calcularProducido(valoresAPagarDeFacturas);
            lbl_gananciasEnFacturas.setText(facturaControla.agregarFormatoMoneda(totalPorFacturas));
            
            //Contamos las facturas que posee el cierre
            lbl_numeroDeFacturas.setText(facturaControla.contarFacturasQueTienenUnCriterioEspecifico(" AND Id_cierre = " + Integer.toString(idCierre)));
            
        }else{
            cargarTablaGestorFacturas();
        }             
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("icons/IconoFactura.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_listaFacturas = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txt_codigoFactura = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jDate_fechaDesde = new com.toedter.calendar.JDateChooser();
        jDate_fechaHasta = new com.toedter.calendar.JDateChooser();
        btn_buscar = new javax.swing.JButton();
        cmb_usuarios = new javax.swing.JComboBox<>();
        btn_generaPDFFacturas = new javax.swing.JButton();
        jLabel17 = new javax.swing.JLabel();
        lbl_gananciasEnFacturas = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbl_numeroDeFacturas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        table_listaFacturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Fecha ", "Código", "Usuario", "Valor ($)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table_listaFacturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_listaFacturasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_listaFacturas);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar por"));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Codigo:");

        txt_codigoFactura.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_codigoFacturaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_codigoFacturaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_codigoFacturaKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Usuario:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Desde:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Hasta:");

        jDate_fechaDesde.setDateFormatString("yyyy-MM-dd");

        jDate_fechaHasta.setDateFormatString("yyyy-MM-dd");

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        cmb_usuarios.setAutoscrolls(true);
        cmb_usuarios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_usuariosItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_codigoFactura)
                    .addComponent(cmb_usuarios, 0, 131, Short.MAX_VALUE))
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDate_fechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDate_fechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btn_buscar)
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txt_codigoFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jDate_fechaDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmb_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jDate_fechaHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_generaPDFFacturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/generarPDF.png"))); // NOI18N
        btn_generaPDFFacturas.setText("Generar Informe PDF");
        btn_generaPDFFacturas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_generaPDFFacturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generaPDFFacturasActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Total ganancias:");

        lbl_gananciasEnFacturas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_gananciasEnFacturas.setForeground(new java.awt.Color(0, 51, 255));
        lbl_gananciasEnFacturas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_gananciasEnFacturas.setText("0,00");

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("N° de facturas:");

        lbl_numeroDeFacturas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_numeroDeFacturas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_numeroDeFacturas.setText("0,00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_generaPDFFacturas)
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_gananciasEnFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl_numeroDeFacturas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(37, 37, 37)
                .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 1, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btn_generaPDFFacturas, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_numeroDeFacturas)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_gananciasEnFacturas)
                            .addComponent(jLabel17))))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void txt_codigoFacturaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigoFacturaKeyTyped
        //Cuenta la cantidad maxima de caracteres
        int numeroCaracteres = 10;
        if(txt_codigoFactura.getText().length() == numeroCaracteres){
            evt.consume();
            JOptionPane.showMessageDialog(null,"Solo 10 caracteres");
            txt_codigoFactura.setText("");
        } 
    }//GEN-LAST:event_txt_codigoFacturaKeyTyped

    private void txt_codigoFacturaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigoFacturaKeyReleased

    }//GEN-LAST:event_txt_codigoFacturaKeyReleased

    private void txt_codigoFacturaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_codigoFacturaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            Limpiar();
            cargarTablaGestorFacturas();
            System.out.println("variable en cuestion: "+hayFacturaVisualizandose);
        }
    }//GEN-LAST:event_txt_codigoFacturaKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrarGestorFacturas();
    }//GEN-LAST:event_formWindowClosing

    private void table_listaFacturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_listaFacturasMouseClicked
        int seleccion = table_listaFacturas.getSelectedRow();
        Filas = seleccion;
    }//GEN-LAST:event_table_listaFacturasMouseClicked

    private void btn_generaPDFFacturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generaPDFFacturasActionPerformed
        //facturaControla.generarReportePDFdeFacturasGeneradas();
        btn_generaPDFFacturas.setEnabled(false);
    }//GEN-LAST:event_btn_generaPDFFacturasActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
       
        String codigo = txt_codigoFactura.getText();
        String sentenciaSQL = "SELECT facturas.Fecha_factura, facturas.Codigo, usuarios.Usuario, facturas.Valor_a_pagar FROM facturas INNER JOIN usuarios ON facturas.Facturado_por = usuarios.Id_usuario WHERE 1=1";
        String sentenciaParaCalculoDeTotal = "";
        int usuarios_cmb = cmb_usuarios.getSelectedIndex();
        Date fecha_desde = jDate_fechaDesde.getDate();
        Date fecha_hasta = jDate_fechaHasta.getDate();
                       
        //Validamos que ningun campo haya quedado en blanco y que almenos uno haya sido diligenciado
        if(codigo.equals("") && usuarios_cmb == 0 && fecha_desde == null && fecha_hasta == null){
            JOptionPane.showMessageDialog(null,"Debe diligenciar por lo menos un criterio de busqueda.");
            cargarTablaGestorFacturas();
        
        }else{
            
            if(!codigo.equals("")){
                //Agregamos el codigo de la factura a la sentencia sql
                sentenciaSQL = sentenciaSQL + " AND facturas.Codigo LIKE '%"+codigo+"%'";
                sentenciaParaCalculoDeTotal = sentenciaParaCalculoDeTotal + " AND facturas.Codigo LIKE '%"+codigo+"%'";
            }
            
            if(usuarios_cmb != 0){
                //Capturamos el objeto usuario para validar el verdadero id en base de datos
                Usuario usuarioSeleccionado = (Usuario)cmb_usuarios.getSelectedItem();
                
                //Validamos el verdadero id del parqueadero, del convenio y de la tarifa en bd
                int idRealDelUsuarioSeleccionado = usuarioControla.consultarIdDeunUsuario(usuarioSeleccionado.getUsuario());
                String idUsuarioReal = Integer.toString(idRealDelUsuarioSeleccionado);
                //Agregamos el id del usuario a la sentencia sql
                sentenciaSQL = sentenciaSQL + " AND facturas.Facturado_por = " + idUsuarioReal; 
                sentenciaParaCalculoDeTotal = sentenciaParaCalculoDeTotal + " AND facturas.Facturado_por = " + idUsuarioReal;
            }
            
            //Ajustamos el formato de las fechas desde y hasta seleccionadas (solo si son diferentes a null)
            if(fecha_desde != null && fecha_hasta != null){
                long lngfecha_desde = fecha_desde.getTime();
                long lngfecha_hasta = fecha_hasta.getTime();
                
                //Validamos que la fecha hasta sea mayor a la fecha desde                
                if(lngfecha_hasta > lngfecha_desde){
                    java.sql.Date sqldateFecha_desde = new java.sql.Date(lngfecha_desde);
                    java.sql.Date sqldateFecha_hasta = new java.sql.Date(lngfecha_hasta);                
                    sentenciaSQL = sentenciaSQL + " AND facturas.Fecha_factura BETWEEN '"+sqldateFecha_desde+"' AND '"+sqldateFecha_hasta+"'";
                    sentenciaParaCalculoDeTotal = sentenciaParaCalculoDeTotal + " AND facturas.Fecha_factura BETWEEN '"+sqldateFecha_desde+"' AND '"+sqldateFecha_hasta+"'";
                
                }else{
                    JOptionPane.showMessageDialog(null,"La Fecha hasta debe ser mayor a la Fecha desde.");
                }     
            }
                       
           //Ejecutamos la sentencia SQL construida
           facturaControla.buscarFactura(sentenciaSQL);
           
           //Calculamos el totalde ganancias por facturas teniendo en cuenta lasentencia sql previamente construida
           //Obtenemos los valores a pagar de las facturas para hacer calculo del total por facturas
           valoresAPagarDeFacturas = facturaControla.obtenerValoresAPagarFacturasBajoAlgunCriterio(sentenciaParaCalculoDeTotal);

           //Calculamos el total por facturas teniendo en cuenta los valores de pagar de las facturas obtenidas
           totalPorFacturas = facturaControla.calcularProducido(valoresAPagarDeFacturas);
           lbl_gananciasEnFacturas.setText(facturaControla.agregarFormatoMoneda(totalPorFacturas));
           
           //Contamos las facturas que cumplen con el o l os criterios de busqueda
           lbl_numeroDeFacturas.setText(facturaControla.contarFacturasQueTienenUnCriterioEspecifico(sentenciaParaCalculoDeTotal));
        }       
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void cmb_usuariosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_usuariosItemStateChanged

    }//GEN-LAST:event_cmb_usuariosItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarFacturas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    //Esto cambia la apariencia de la app para que se acomode al Siste Operativo
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    new GestionarFacturas().setVisible(true);
                } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    //Logger.getLogger(GestionarFacturas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_buscar;
    public static javax.swing.JButton btn_generaPDFFacturas;
    private javax.swing.JComboBox<String> cmb_usuarios;
    private com.toedter.calendar.JDateChooser jDate_fechaDesde;
    private com.toedter.calendar.JDateChooser jDate_fechaHasta;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_gananciasEnFacturas;
    private javax.swing.JLabel lbl_numeroDeFacturas;
    public static javax.swing.JTable table_listaFacturas;
    private javax.swing.JTextField txt_codigoFactura;
    // End of variables declaration//GEN-END:variables

    //Metodo que se invoca al cerrar el jFrame
    private void cerrarGestorFacturas(){
        
        if(idCierre != 1){
            String botones[] = {"Cerrar", "Cancelar"};
            int eleccion = JOptionPane.showOptionDialog(this, "¿Está seguro que desea cerrar?", "Administrador de facturas", 0, 3, null, botones, this);

            if(eleccion == JOptionPane.YES_OPTION){
                dispose();
                //Avisamos que esta ventana se encuentra cerrada 
                MenuAdministrador.hayAlgunaVentanaAbiertaDelSistema = false;
                new EditarCierreDeCaja().setVisible(true);
            }
        
        }else{
            String botones[] = {"Si", "No"};
            int eleccion = JOptionPane.showOptionDialog(this, "¿Está seguro que desea cerrar?", "Administrador de facturas", 0, 3, null, botones, this);

            if(eleccion == JOptionPane.YES_OPTION){
                dispose();
                //Avisamos que esta ventana se encuentra cerrada 
                MenuAdministrador.hayAlgunaVentanaAbiertaDelSistema = false;
                PanelReportes.btn_facturas.setEnabled(true);
            }
        }        
    }
     
    //Metodo que limpia el formulario en caso de ingresar tablero principal
    public void Limpiar(){
        txt_codigoFactura.setText("");
        cmb_usuarios.setSelectedIndex(0);
        jDate_fechaDesde.setDate(null);
        jDate_fechaHasta.setDate(null);
    } 
    
    //Metodo quecarga la tabla del administrador de facturas
    public void cargarTablaGestorFacturas(){
        facturaControla.cargarTablaAdministradorDeFacturas();
            
        //Calculamos el total de ganancias por facturas de todas las facturas del sistema
        //Obtenemos los valores a pagar de las facturas para hacer calculo del total por facturas
        valoresAPagarDeFacturas = facturaControla.obtenerValoresAPagarFacturasBajoAlgunCriterio("");

        //Calculamos el total por facturas teniendo en cuenta los valores de pagar de las facturas obtenidas
        totalPorFacturas = facturaControla.calcularProducido(valoresAPagarDeFacturas);
        lbl_gananciasEnFacturas.setText(facturaControla.agregarFormatoMoneda(totalPorFacturas));
        
        //Contamos las facturas
        lbl_numeroDeFacturas.setText(facturaControla.contarFacturasQueTienenUnCriterioEspecifico(""));
    }
    
}


