package vista;

import controlador.ConvenioControlador;
import controlador.FacturaControlador;
import controlador.ParametroControlador;
import controlador.ParqueaderoControlador;
import controlador.TarifaControlador;
import controlador.UsuarioControlador;
import controlador.VehiculoControlador;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import modelo.Convenio;
import modelo.Factura;
import modelo.Parqueadero;
import modelo.Tarifa;
import modelo.Vehiculo;
import org.apache.log4j.Logger;


/**
 *
 * @author ALEJO
 */
public class GestionarBicisyOtros extends javax.swing.JFrame implements Runnable {
    Vehiculo nuevoVehiculo = new Vehiculo(0, "", "", "", "", "", "", "", 0, 0, 0);  
    Factura nuevaFactura = new Factura(0, "", "", 0, "", "", "", "", "", 0, 0, "", "", 0, 0, "", 0, "", "", "", "", "", "");
    VehiculoControlador vehiControla = new VehiculoControlador();
    ParametroControlador paramControla = new ParametroControlador();
    ParqueaderoControlador parqControla = new ParqueaderoControlador();
    ConvenioControlador convenioControla = new ConvenioControlador();
    TarifaControlador tarifaControla = new TarifaControlador();
    FacturaControlador facturaControla = new FacturaControlador();
    UsuarioControlador usuarioControla = new UsuarioControlador();
        
    public static String biciUOtro_update;
    public static boolean hayBiciUOtroEnEdicion = false;
    String user = "";
    public static String tipoIdentificacion;
    public static String identificacion;
    public static String dueñoBiciUOtro;
    public static String tipoVehiculoBiciUOtro;
    
    public static DefaultTableModel modeloBicisUOtros;
    int Fila;
    
    //Declaramos los objetos  y se los aprovisionamos a su combobox
    Parqueadero parq = new Parqueadero();
    Convenio conv = new Convenio();
    Tarifa tarif = new Tarifa();
    
    Thread hilo1 = new Thread(this);
    Thread hilo2 = new Thread(this);
    Thread hilo3 = new Thread(this);
       
    private final Logger log = Logger.getLogger(GestionarBicisyOtros.class);
    private URL url = GestionarBicisyOtros.class.getResource("Log4j.properties");
    
    /**
     * Creates new form nuevoUsuario
     */
    public GestionarBicisyOtros() {       
        initComponents();
        user = Login.usuario;
        setSize(686, 600);
        setResizable(false);
        setTitle("Gestionar bicicletas y otros vehiculos");
        setLocationRelativeTo(null);
        setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        
        //Ejecutamos los hilos de loc combo de parqueaderos convenios y tarifas
        hilo1.start();
        hilo2.start();
        hilo3.start(); 
        
        //Avisamos que esta ventana se encuentra abierta para que no deje cerrar sesion al usuario
        MenuAdministrador.hayAlgunaVentanaAbiertaDelSistema = true; 
        vehiControla.cargarTablaDeBicicletasYOtrosVehiculos();
        //Cargamos el proceso que se encarga de registrar el ticket qr de bicicletas y otros
        vehiControla.cargarProcesoDeRegistroQRBicisYOtros();
        
        //Agregamos la funcion de editar vehiculo al hacer click sobre el registro de la tabla
        Table_listaBicisYOtros.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e){
            int fila_point =  Table_listaBicisYOtros.rowAtPoint(e.getPoint());
            int columna_point = 0;

            if(fila_point > -1){
                biciUOtro_update = (String) modeloBicisUOtros.getValueAt(fila_point, columna_point);              
            }
        }
    });
    }
    
    @Override
    public Image getIconImage() {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("icons/bicicleta.png"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Table_listaBicisYOtros = new javax.swing.JTable();
        btn_generarReporteBicisyOtros = new javax.swing.JButton();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txt_noIdentificacion = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_ingresar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cmb_tipoVehiculo = new javax.swing.JComboBox<>();
        btn_editar = new javax.swing.JButton();
        btn_eliminar = new javax.swing.JButton();
        btn_generarQR = new javax.swing.JButton();
        cmb_tipoIdentificacion = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_propietario = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txt_colorVehiculo = new javax.swing.JTextField();
        cmb_tarifa = new javax.swing.JComboBox<>();
        cmb_convenios = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmb_parqueaderos = new javax.swing.JComboBox<>();
        check_estaVehiculoEnParqueadero = new javax.swing.JCheckBox();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cmb_tipoVehiculoBusqueda = new javax.swing.JComboBox<>();
        btn_buscar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        cmb_tipoIdentificacionBusqueda = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txt_noIdentificacionBusqueda = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txt_propietarioBusqueda = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setIconImage(getIconImage());
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        Table_listaBicisYOtros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Tipo identif", "N° identificación", "Propietario", "Tipo", "N° parq", "Color", "Convenio", "Tarifa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_listaBicisYOtros.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        Table_listaBicisYOtros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_listaBicisYOtrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_listaBicisYOtros);

        btn_generarReporteBicisyOtros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/generarPDF.png"))); // NOI18N
        btn_generarReporteBicisyOtros.setText("Generar Informe PDF");
        btn_generarReporteBicisyOtros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_generarReporteBicisyOtros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarReporteBicisyOtrosActionPerformed(evt);
            }
        });

        txt_noIdentificacion.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_noIdentificacionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_noIdentificacionFocusLost(evt);
            }
        });
        txt_noIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_noIdentificacionActionPerformed(evt);
            }
        });
        txt_noIdentificacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_noIdentificacionKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Tipo de identificación:");

        btn_ingresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Save_icon-icons.com_73702.png"))); // NOI18N
        btn_ingresar.setText("Guardar");
        btn_ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Tipo de vehiculo:");

        cmb_tipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "BICICLETA", "PATINETA", "OTRO" }));

        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit-validated_40458.png"))); // NOI18N
        btn_editar.setText("Editar");
        btn_editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_editar.setEnabled(false);
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic_delete_128_28267.png"))); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_eliminar.setEnabled(false);
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });

        btn_generarQR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/qr.png"))); // NOI18N
        btn_generarQR.setText("QR");
        btn_generarQR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_generarQR.setEnabled(false);
        btn_generarQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarQRActionPerformed(evt);
            }
        });

        cmb_tipoIdentificacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Cedula de ciudadanía", "Targeta de identidad", "Registro civil", "Pasaporte", "Targeta de extrangería", "NIT", "Permiso permanencia", "DIE" }));
        cmb_tipoIdentificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tipoIdentificacionActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("N° documento:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel10.setText("Propietario:");

        txt_propietario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_propietarioFocusGained(evt);
            }
        });
        txt_propietario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_propietarioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_propietarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_propietarioKeyTyped(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel11.setText("Color:");

        txt_colorVehiculo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_colorVehiculoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_colorVehiculoFocusLost(evt);
            }
        });
        txt_colorVehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_colorVehiculoActionPerformed(evt);
            }
        });
        txt_colorVehiculo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_colorVehiculoKeyTyped(evt);
            }
        });

        cmb_tarifa.setAutoscrolls(true);
        cmb_tarifa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_tarifaItemStateChanged(evt);
            }
        });
        cmb_tarifa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmb_tarifaFocusGained(evt);
            }
        });

        cmb_convenios.setAutoscrolls(true);
        cmb_convenios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_conveniosItemStateChanged(evt);
            }
        });
        cmb_convenios.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmb_conveniosFocusGained(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Convenio:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Tarifa:");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("N° de Parqueadero:");

        cmb_parqueaderos.setAutoscrolls(true);
        cmb_parqueaderos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmb_parqueaderosFocusGained(evt);
            }
        });

        check_estaVehiculoEnParqueadero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        check_estaVehiculoEnParqueadero.setText("Está en parqueadero");
        check_estaVehiculoEnParqueadero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_estaVehiculoEnParqueaderoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_parqueaderos, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_colorVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_tipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_propietario, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_noIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_tipoIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_ingresar)
                            .addComponent(btn_editar)
                            .addComponent(btn_eliminar)
                            .addComponent(btn_generarQR)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_convenios, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_tarifa, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(check_estaVehiculoEnParqueadero)))
                .addGap(698, 698, 698))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_tipoIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmb_tipoVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txt_colorVehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_noIdentificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txt_propietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_parqueaderos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_eliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_generarQR)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(cmb_tarifa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(cmb_convenios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)
                                .addComponent(jLabel13)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(check_estaVehiculoEnParqueadero)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jTabbedPane3.addTab("Registro", jPanel1);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Tipo de vehiculo:");

        cmb_tipoVehiculoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "BICICLETA", "PATINETA", "OTRO" }));

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Tipo de identificación:");

        cmb_tipoIdentificacionBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Cedula de ciudadanía", "Targeta de identidad", "Registro civil", "Pasaporte", "Targeta de extrangería", "NIT", "Permiso permanencia", "DIE", " ", " " }));
        cmb_tipoIdentificacionBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tipoIdentificacionBusquedaActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel14.setText("N° documento:");

        txt_noIdentificacionBusqueda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_noIdentificacionBusquedaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_noIdentificacionBusquedaFocusLost(evt);
            }
        });
        txt_noIdentificacionBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_noIdentificacionBusquedaActionPerformed(evt);
            }
        });
        txt_noIdentificacionBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_noIdentificacionBusquedaKeyTyped(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel15.setText("Propietario:");

        txt_propietarioBusqueda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_propietarioBusquedaFocusGained(evt);
            }
        });
        txt_propietarioBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_propietarioBusquedaActionPerformed(evt);
            }
        });
        txt_propietarioBusqueda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_propietarioBusquedaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_propietarioBusquedaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_propietarioBusquedaKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmb_tipoIdentificacionBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_noIdentificacionBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_propietarioBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cmb_tipoVehiculoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 185, Short.MAX_VALUE)
                        .addComponent(btn_buscar)
                        .addGap(60, 60, 60))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_tipoIdentificacionBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_noIdentificacionBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_propietarioBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_tipoVehiculoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(101, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34))))
        );

        jTabbedPane3.addTab("Buscar", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_generarReporteBicisyOtros, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 659, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_generarReporteBicisyOtros, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Metodo boton generar pdf del reporte de parqueaderos
    private void btn_generarReporteBicisyOtrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarReporteBicisyOtrosActionPerformed
        String sentenciaSQLParaReporte = " AND vehiculos.TipoVehiculo IN ('BICICLETA', 'PATINETA', 'OTRO')";
        int tipoIdentificacion_cmb = cmb_tipoIdentificacionBusqueda.getSelectedIndex(); 
        String tipoIdentifStr = "";
        String identificacion = txt_noIdentificacionBusqueda.getText();
        String propietario = txt_propietarioBusqueda.getText();
        int tipoVehiculo_cmb = cmb_tipoVehiculoBusqueda.getSelectedIndex();
        String tipoVehiculo_str = (String) cmb_tipoVehiculoBusqueda.getSelectedItem();
        

        //Validamos que ningun campo haya quedado en blanco y que al menos uno haya sido diligenciado
        if(tipoIdentificacion_cmb == 0 && identificacion.equals("") && propietario.equals("") && tipoVehiculo_cmb == 0){
            vehiControla.generarReportePDFdeBicisYOtrosRegistradas(sentenciaSQLParaReporte);
            btn_generarReporteBicisyOtros.setEnabled(false);

        }else{
            if(tipoIdentificacion_cmb != 0){
                
                if(tipoIdentificacion_cmb == 1){
                    tipoIdentifStr = "CC";
                }else if(tipoIdentificacion_cmb == 2){
                    tipoIdentifStr = "TI";
                }else if(tipoIdentificacion_cmb == 3){
                    tipoIdentifStr = "RC";
                }else if(tipoIdentificacion_cmb == 4){
                    tipoIdentifStr = "PA";
                }else if(tipoIdentificacion_cmb == 5){
                    tipoIdentifStr = "TE";
                }else if(tipoIdentificacion_cmb == 6){
                    tipoIdentifStr = "NIT";
                }else if(tipoIdentificacion_cmb == 7){
                    tipoIdentifStr = "PP";
                }else if(tipoIdentificacion_cmb == 8){
                    tipoIdentifStr = "DIE";
                }

                //Agregamos la placa del vehiculo a la sentencia sql
                sentenciaSQLParaReporte = sentenciaSQLParaReporte + " AND vehiculos.Tipo_Identificacion = '"+tipoIdentifStr+"'";
            }
            
            if(!identificacion.equals("")){
                //Agregamos propietario del vehiculo a la sentencia sql
                sentenciaSQLParaReporte = sentenciaSQLParaReporte + " AND vehiculos.No_identificacion LIKE '%"+identificacion+"%'";
            }
            
            if(!propietario.equals("")){
                //Agregamos propietario del vehiculo a la sentencia sql
                sentenciaSQLParaReporte = sentenciaSQLParaReporte + " AND vehiculos.Propietario LIKE '%"+propietario+"%'";
            }

            if(tipoVehiculo_cmb != 0){
                //Agregamos tipo de vehiculo a la sentencia sql
                sentenciaSQLParaReporte= sentenciaSQLParaReporte + " AND vehiculos.TipoVehiculo = '"+tipoVehiculo_str+"'";
            }

            //Ejecutamos la sentencia SQL construida
            vehiControla.generarReportePDFdeBicisYOtrosRegistradas(sentenciaSQLParaReporte);
            btn_generarReporteBicisyOtros.setEnabled(false);
            
        }
    }//GEN-LAST:event_btn_generarReporteBicisyOtrosActionPerformed

    //Aqui programamos lo que queremos quehaga al cerrar el jframe
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        cerrarGestorBibicletasYOtrosVehiculos();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void txt_noIdentificacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_noIdentificacionFocusGained
        btn_eliminar.setEnabled(false);
        btn_ingresar.setEnabled(true);
        btn_generarQR.setEnabled(false);
        btn_editar.setEnabled(false);
    }//GEN-LAST:event_txt_noIdentificacionFocusGained

    private void txt_noIdentificacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_noIdentificacionFocusLost
        btn_eliminar.setEnabled(true);
    }//GEN-LAST:event_txt_noIdentificacionFocusLost

    private void txt_noIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_noIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noIdentificacionActionPerformed

    private void txt_noIdentificacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_noIdentificacionKeyTyped
        //Forza aescribir en mayuscula
        char c=evt.getKeyChar();
        if(Character.isLowerCase(c)){
            evt.setKeyChar(Character.toUpperCase(c));
        }

        //Cuenta la cantidad maxima de caracteres
        int numeroCaracteres = 15;
        if(txt_noIdentificacion.getText().length()== numeroCaracteres){
            evt.consume();
            JOptionPane.showMessageDialog(null,"Solo 15 caracteres.", "Validación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/advertencia.png", 32, 32));
            txt_noIdentificacion.setText("");
        }
    }//GEN-LAST:event_txt_noIdentificacionKeyTyped

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        
        int tipoIdentif_cmb = 0, tipoVehiculo_cmb = 0, parqueadero_cmb, validacion = 0;
        String qrInfo, color = "";                
        tipoIdentif_cmb = cmb_tipoIdentificacion.getSelectedIndex();
        identificacion = txt_noIdentificacion.getText().trim();
        dueñoBiciUOtro = txt_propietario.getText().trim();
        tipoVehiculo_cmb = cmb_tipoVehiculo.getSelectedIndex();
        parqueadero_cmb = cmb_parqueaderos.getSelectedIndex();
        color = txt_colorVehiculo.getText().trim();
        
        Parqueadero parqSeleccionado = new Parqueadero();
        Convenio convSeleccionado = new Convenio();
        Tarifa tarifSeleccionada = new Tarifa();     
        
        //Capturamos el objeto parqueadero, convenio y tarifa para validarles verdadero id en base de datos
        parqSeleccionado = (Parqueadero)cmb_parqueaderos.getSelectedItem();
        convSeleccionado = (Convenio)cmb_convenios.getSelectedItem();
        tarifSeleccionada = (Tarifa)cmb_tarifa.getSelectedItem();
        
        boolean BiciUOtroEnParqueadero = check_estaVehiculoEnParqueadero.isSelected();
        String BiciUOtroEstaEnParqueo;
        
        if(tipoIdentif_cmb == 0){
            tipoIdentificacion = "Seleccione";
            cmb_tipoIdentificacion.setBackground(Color.red);
            validacion++;
        }else if(tipoIdentif_cmb == 1){
            tipoIdentificacion = "CC";
        }else if(tipoIdentif_cmb == 2){
            tipoIdentificacion = "TI";
        }else if(tipoIdentif_cmb == 3){
            tipoIdentificacion = "RC";
        }else if(tipoIdentif_cmb == 4){
            tipoIdentificacion = "PA";
        }else if(tipoIdentif_cmb == 5){
            tipoIdentificacion = "TE";
        }else if(tipoIdentif_cmb == 6){
            tipoIdentificacion = "NIT";
        }else if(tipoIdentif_cmb == 7){
            tipoIdentificacion = "PP";
        }else if(tipoIdentif_cmb == 8){
            tipoIdentificacion = "DIE";
        }
                                          
        if(identificacion.equals("")){
            txt_noIdentificacion.setBackground(Color.red);
            validacion++;
        }
        if(dueñoBiciUOtro.equals("")){
            txt_propietario.setBackground(Color.red);
            validacion++;
        }
        
        if(tipoVehiculo_cmb == 0){
            tipoVehiculoBiciUOtro = "Seleccione";
            cmb_tipoVehiculo.setBackground(Color.red);
            validacion++;
        }else if(tipoVehiculo_cmb == 1){
            tipoVehiculoBiciUOtro = "BICICLETA";
        }else if(tipoVehiculo_cmb == 2){
            tipoVehiculoBiciUOtro = "PATINETA";
        }else if(tipoVehiculo_cmb == 3){
            tipoVehiculoBiciUOtro = "OTRO";
        }
        
        if(color.equals("")){
            txt_colorVehiculo.setBackground(Color.red);
            validacion++;
        }
        
        if(parqueadero_cmb==0){
            cmb_parqueaderos.setBackground(Color.red);
            validacion++;
        }      
        
        if(hayBiciUOtroEnEdicion == true){
            JOptionPane.showMessageDialog(null, "No Permitido, cierre la ventana de edición de vehiculos para continuar.", "Validación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/advertencia.png", 32, 32));
            txt_noIdentificacion.requestFocus();
            validacion++;
        }
        
        if(BiciUOtroEnParqueadero){
            BiciUOtroEstaEnParqueo = "Si";
        }else{
            BiciUOtroEstaEnParqueo = "No";
        }
                
        int vehiculoYaPreviamenteRegistrado = vehiControla.evaluarExistenciaDelVehiculo(null, null, tipoIdentificacion, identificacion);
        
        if(vehiculoYaPreviamenteRegistrado == 1){
            JOptionPane.showMessageDialog(null, "El vehiculo ya se encuentra registrado.", "Validación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/advertencia.png", 32, 32));
            txt_noIdentificacion.setText("");
            validacion++;
        }      
        
        int idRealDelParqueaderoSeleccionado = parqControla.consultarIdParqueadero(parqSeleccionado.getNombre());
        //Validamos el verdadero id del parqueadero en bd        
        boolean parqueaderoEstaOcupado = parqControla.consultarDisponibilidadDeParqueaderoMedianteID(idRealDelParqueaderoSeleccionado);
        if(parqueaderoEstaOcupado){
            JOptionPane.showMessageDialog(null, "El parqueadero indicado ya se encuentra ocupado.", "Validación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/advertencia.png", 32, 32));
            cmb_parqueaderos.setSelectedIndex(0);
            validacion++;
        }else{
            boolean parqueaderoEsCompatible = parqControla.consultarCompatibilidadDeParqueaderoMedianteID(idRealDelParqueaderoSeleccionado, tipoVehiculoBiciUOtro);
            if(!parqueaderoEsCompatible){
                JOptionPane.showMessageDialog(null, "El parqueadero indicado no es compatible con el vehiculo.", "Validación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/advertencia.png", 32, 32));
                cmb_parqueaderos.setSelectedIndex(0);
                validacion++;  
            }
        }
               
         //Validamos el verdadero id del convenio y de la tarifa en bd
        int idRealDelConvenioSeleccionado = convenioControla.consultarIdDeunConvenio(convSeleccionado.getNombre());
        int idRealDeTarifaSeleccionada = tarifaControla.consultarIdDeunaTarifa(tarifSeleccionada.getNombreTarifa());
             
        if(validacion == 0 ){
            //Reanudamos el proceso de generacion ticket qr vehicular
            vehiControla.reanudarProcesoDeRegistroQRBicisYOtros();
            
            //Encapsulamos el objeto vehiculo 
            nuevoVehiculo.setId(0);
            qrInfo = tipoIdentificacion+identificacion;
            nuevoVehiculo.setQr_consecutivo(qrInfo);
            nuevoVehiculo.setTipoIdentificacion(tipoIdentificacion);
            nuevoVehiculo.setNumIdentificacion(identificacion);
            nuevoVehiculo.setPropietario(dueñoBiciUOtro);
            nuevoVehiculo.setTipoVehiculo(tipoVehiculoBiciUOtro);
            nuevoVehiculo.setColor(color);
            nuevoVehiculo.setId_parqueadero(idRealDelParqueaderoSeleccionado);
            nuevoVehiculo.setId_convenio(idRealDelConvenioSeleccionado);
            nuevoVehiculo.setId_tarifa(idRealDeTarifaSeleccionada); 
            nuevoVehiculo.setEstaEnParqueadero(BiciUOtroEstaEnParqueo);
            
            //Crea el objeto vehiculo en el sistema
            vehiControla.crearVehiculo(nuevoVehiculo);
            
            //Obtenemos el id con el que se registro el vehiculo
            int idDelVehiculo = vehiControla.consultarIdDeUnVehiculo(null, tipoIdentificacion, identificacion);
            
            //Evaluamos si el vehiculo tiene factura abierta
            int vehiculoConFctraAbierta = vehiControla.consultarSiVehiculoTieneFacturasAbiertas(idDelVehiculo,null,null,null);
            
            //Generamos el ingreso del vehiculo en caja dependiendo de si esta o no en parqueadero
            if(BiciUOtroEstaEnParqueo.equals("Si")){
                
                if(vehiculoConFctraAbierta == 1){
                    int idFctra = facturaControla.consultarIdDeUnaFacturaAbierta(null, tipoIdentificacion, identificacion);                    
                    facturaControla.actualizarFacturaAbierta(idFctra, idDelVehiculo, "", "", "", "", "", 0, 0, 0);
                    
                    //Validamos si el parqueadero utilizado por el vehiculo antes de registrarse en el sistema es igual al ingresado por caja
                    int idDelParqDelVehiculoAntesDeSerRegistrado = vehiControla.consultarIdParqQueOcupaUnVehiculo(null, tipoIdentificacion, identificacion);
                    
                    if(idDelParqDelVehiculoAntesDeSerRegistrado != idRealDelParqueaderoSeleccionado){
                       parqControla.liberarParqueadero(tipoVehiculoBiciUOtro, null, tipoIdentificacion, identificacion);
                       parqControla.actualizarEstadoDeParqueadero(tipoVehiculoBiciUOtro, null, tipoIdentificacion, identificacion, dueñoBiciUOtro, idRealDelParqueaderoSeleccionado, BiciUOtroEstaEnParqueo);
                    }
                                        
                }else{
                    //Modelamos la factura de primer ingreso 
                    nuevaFactura.setId(0);
                    nuevaFactura.setCodigo("FAC" + paramControla.generarConsecutivo(10));
                    nuevaFactura.setFechaDeFactura(facturaControla.fecha_de_factura());
                    nuevaFactura.setIdDelVehiculo(idDelVehiculo);
                    nuevaFactura.setFacturadoPor(usuarioControla.consultarIdDeunUsuario(user));
                    nuevaFactura.setEstadoDeFactura("Abierta");
                    nuevaFactura.setEstaContabilizada("No");
                    nuevaFactura.setFechaDeIngresoVehiculo("1990-01-01 23:59:00"); //No generará cobro pues no estamos teniendo en cuenta la hora en que fue ingresado
                    nuevaFactura.setId_cierre(1);

                    //Creamos el objeto Factura de primer ingreso
                    facturaControla.crearFactura(nuevaFactura, true);
                    
                    //Actualizamos el estado del parqueadero
                    parqControla.actualizarEstadoDeParqueadero(tipoVehiculoBiciUOtro, null, tipoIdentificacion, identificacion, dueñoBiciUOtro, idRealDelParqueaderoSeleccionado, BiciUOtroEstaEnParqueo);
                }
                                
            }else{
                if(vehiculoConFctraAbierta == 1){
                    int idFctra = facturaControla.consultarIdDeUnaFacturaAbierta(null, tipoIdentificacion, identificacion); 
                    facturaControla.actualizarFacturaAbierta(idFctra, idDelVehiculo, "", "", "", "", "", 0, 0, 0);
                    
                    //Validamos si el parqueadero utilizado por el vehiculo antes de registrarse en el sistema es igual al ingresado por caja
                    int idDelParqDelVehiculoAntesDeSerRegistrado = vehiControla.consultarIdParqQueOcupaUnVehiculo(null, tipoIdentificacion, identificacion);
                    
                    if(idDelParqDelVehiculoAntesDeSerRegistrado != idRealDelParqueaderoSeleccionado){
                       parqControla.liberarParqueadero(tipoVehiculoBiciUOtro, null, tipoIdentificacion, identificacion);
                       BiciUOtroEstaEnParqueo = "Si";
                       parqControla.actualizarEstadoDeParqueadero(tipoVehiculoBiciUOtro, null, tipoIdentificacion, identificacion, dueñoBiciUOtro, idRealDelParqueaderoSeleccionado, BiciUOtroEstaEnParqueo);
                    }
                    
                }else{
                    parqControla.actualizarEstadoDeParqueadero(tipoVehiculoBiciUOtro, null, tipoIdentificacion, identificacion, dueñoBiciUOtro, idRealDelParqueaderoSeleccionado, BiciUOtroEstaEnParqueo);
                }    
            }    
            
            //Agregamos el objeto vehiculo a la tabla de vehiculos
            Object[] fila = new Object[8];
            fila[0] = tipoIdentificacion;
            fila[1] = identificacion;
            fila[2] = dueñoBiciUOtro;
            fila[3] = tipoVehiculoBiciUOtro;
            fila[4] = parqSeleccionado.getNombre();
            fila[5] = color;
            fila[6] = convSeleccionado.getNombre();
            fila[7] = tarifSeleccionada.getNombreTarifa();
            modeloBicisUOtros.addRow(fila);
            
            JOptionPane.showMessageDialog(null, "Vehiculo registrado satisfactoriamente.", "Confirmación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/exitoso.png", 32, 32));
            //Generamos el codigo QR del vehiculo y lo imprimimos
            vehiControla.generarQR(qrInfo+" - "+dueñoBiciUOtro, qrInfo, tipoVehiculoBiciUOtro);
            Limpiar();
            Normalizar();
            
        }else{
            JOptionPane.showMessageDialog(null, "Debes de llenar todos los campos.", "Validación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/advertencia.png", 32, 32));
            Normalizar();
        }
    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed

        String sentenciaSQL = "SELECT Ve.Tipo_Identificacion, Ve.No_identificacion, Ve.Propietario, Ve.TipoVehiculo, Parq.Nombre_parqueadero, Ve.Color, Conv.Nombre_convenio, Tar.Nombre_tarifa FROM vehiculos Ve INNER JOIN parqueaderos Parq ON Ve.Id_parqueadero = Parq.Id_parqueadero INNER JOIN convenios Conv ON Ve.Id_convenio = Conv.Id_convenio INNER JOIN tarifas Tar ON Ve.Id_tarifa = Tar.Id_tarifa WHERE Ve.TipoVehiculo IN ('BICICLETA', 'PATINETA', 'OTRO')";
        int tipoIdentificacion_cmb = cmb_tipoIdentificacionBusqueda.getSelectedIndex(); 
        String tipoIdentifStr = "";
        String identificacion = txt_noIdentificacionBusqueda.getText();
        String propietario = txt_propietarioBusqueda.getText();
        int tipoVehiculo_cmb = cmb_tipoVehiculoBusqueda.getSelectedIndex();
        String tipoVehiculo_str = (String) cmb_tipoVehiculoBusqueda.getSelectedItem();
        
     
        //Validamos que ningun campo haya quedado en blanco y que al menos uno haya sido diligenciado
        if(tipoIdentificacion_cmb == 0 && identificacion.equals("") && propietario.equals("") && tipoVehiculo_cmb == 0){
            JOptionPane.showMessageDialog(null,"Debe diligenciar por lo menos un criterio de busqueda.", "Validación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/advertencia.png", 32, 32));
            vehiControla.cargarTablaDeBicicletasYOtrosVehiculos();
        }else{
            if(tipoIdentificacion_cmb != 0){
                
                if(tipoIdentificacion_cmb == 1){
                    tipoIdentifStr = "CC";
                }else if(tipoIdentificacion_cmb == 2){
                    tipoIdentifStr = "TI";
                }else if(tipoIdentificacion_cmb == 3){
                    tipoIdentifStr = "RC";
                }else if(tipoIdentificacion_cmb == 4){
                    tipoIdentifStr = "PA";
                }else if(tipoIdentificacion_cmb == 5){
                    tipoIdentifStr = "TE";
                }else if(tipoIdentificacion_cmb == 6){
                    tipoIdentifStr = "NIT";
                }else if(tipoIdentificacion_cmb == 7){
                    tipoIdentifStr = "PP";
                }else if(tipoIdentificacion_cmb == 8){
                    tipoIdentifStr = "DIE";
                }

                //Agregamos la placa del vehiculo a la sentencia sql
                sentenciaSQL = sentenciaSQL + " AND Ve.Tipo_Identificacion = '"+tipoIdentifStr+"'";
            }
            
            if(!identificacion.equals("")){
                //Agregamos propietario del vehiculo a la sentencia sql
                sentenciaSQL = sentenciaSQL + " AND Ve.No_identificacion LIKE '%"+identificacion+"%'";
            }
            
            if(!propietario.equals("")){
                //Agregamos propietario del vehiculo a la sentencia sql
                sentenciaSQL = sentenciaSQL + " AND Ve.Propietario LIKE '%"+propietario+"%'";
            }

            if(tipoVehiculo_cmb != 0){
                //Agregamos tipo de vehiculo a la sentencia sql
                sentenciaSQL = sentenciaSQL + " AND Ve.TipoVehiculo = '"+tipoVehiculo_str+"'";
            }
        }
        //Ejecutamos la sentencia SQL construida
        vehiControla.buscarBicicletasUOtros(sentenciaSQL);
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        Fila = Table_listaBicisYOtros.getSelectedRow();
        int cantidadFilas = Table_listaBicisYOtros.getSelectedRowCount();

        if(cantidadFilas == 0){
            JOptionPane.showMessageDialog(null, "Seleccione el vehiculo que desea editar.", "Validación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/advertencia.png", 32, 32));
        }else{

            if(hayBiciUOtroEnEdicion == true){
                JOptionPane.showMessageDialog(null, "No Permitido.", "Error", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/Cancelar.png", 32, 32));
            }else{
                hayBiciUOtroEnEdicion = true;
                biciUOtro_update = Table_listaBicisYOtros.getValueAt(Fila, 0).toString() + Table_listaBicisYOtros.getValueAt(Fila, 1).toString();
                new EditarBicisYOtros().setVisible(true);
            }
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed

        Fila = Table_listaBicisYOtros.getSelectedRow();
        int cantidadFilas = Table_listaBicisYOtros.getSelectedRowCount();

        if(cantidadFilas == 0){
            JOptionPane.showMessageDialog(null, "Seleccione el vehiculo que desea eliminar.", "Validación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/advertencia.png", 32, 32));
        }else{
            String tipoIdentif = Table_listaBicisYOtros.getValueAt(Fila, 0).toString();
            String identificacion = Table_listaBicisYOtros.getValueAt(Fila, 1).toString();
            int idDelVehiculo = vehiControla.consultarIdDeUnVehiculo(null, tipoIdentif, identificacion);
            String propietario = Table_listaBicisYOtros.getValueAt(Fila, 2).toString();
            tipoVehiculoBiciUOtro = Table_listaBicisYOtros.getValueAt(Fila, 3).toString();
                   
            String botones[] = {"Si", "No"};
            int decision = JOptionPane.showOptionDialog(this, "¿Está seguro que desea eliminar?", "Eliminar vehiculo", 0, JOptionPane.QUESTION_MESSAGE, paramControla.getIcon("/icons/pregunta.png", 32, 32), botones, this);

            if(decision == JOptionPane.YES_OPTION){

                vehiControla.eliminarVehiculo(idDelVehiculo);

                int elvehiculoTieneFacturaAbierta = vehiControla.consultarSiVehiculoTieneFacturasAbiertas(idDelVehiculo,null, tipoIdentif, identificacion);

                if(elvehiculoTieneFacturaAbierta == 1){
                    facturaControla.eliminarFacturaAbierta(idDelVehiculo,null, null, null);
                }

                JOptionPane.showMessageDialog(null, "El vehiculo ha sido eliminado", "Confirmación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/exitoso.png", 32, 32));
                //Eliminamos el codigo qr del vehiculo
                vehiControla.eliminarQr(tipoIdentif+identificacion+" - "+propietario, tipoVehiculoBiciUOtro);
                modeloBicisUOtros.removeRow(Fila);
                parqControla.liberarParqueadero(tipoVehiculoBiciUOtro, null, tipoIdentif, identificacion);
                Limpiar();

            }else if(decision == JOptionPane.NO_OPTION){
                btn_ingresar.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    private void btn_generarQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarQRActionPerformed
        Fila = Table_listaBicisYOtros.getSelectedRow();
        int cantidadFilas = Table_listaBicisYOtros.getSelectedRowCount();

        if(cantidadFilas == 0){
            JOptionPane.showMessageDialog(null, "Seleccione el vehiculo al que desea generar su codigo qr.", "Validación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/advertencia.png", 32, 32));
        }else{
            tipoIdentificacion = Table_listaBicisYOtros.getValueAt(Fila, 0).toString();
            identificacion = Table_listaBicisYOtros.getValueAt(Fila, 1).toString();
            dueñoBiciUOtro = Table_listaBicisYOtros.getValueAt(Fila, 2).toString();
            tipoVehiculoBiciUOtro = Table_listaBicisYOtros.getValueAt(Fila, 3).toString();
            vehiControla.generarTicketQrVehiculo(tipoIdentificacion+identificacion+" - "+dueñoBiciUOtro, false, "", tipoVehiculoBiciUOtro);
            JOptionPane.showMessageDialog(null, "Codigo qr generado satisfactoriamente.", "Confirmación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/exitoso.png", 32, 32));
        }
    }//GEN-LAST:event_btn_generarQRActionPerformed

    private void cmb_tipoIdentificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tipoIdentificacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_tipoIdentificacionActionPerformed

    private void txt_propietarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_propietarioFocusGained
        btn_eliminar.setEnabled(false);
        btn_ingresar.setEnabled(true);
        btn_generarQR.setEnabled(false);
        btn_editar.setEnabled(false);
    }//GEN-LAST:event_txt_propietarioFocusGained

    private void txt_propietarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_propietarioKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            Limpiar();
            btn_eliminar.setEnabled(false);
            btn_ingresar.setEnabled(true);
            btn_generarQR.setEnabled(false);
        }
    }//GEN-LAST:event_txt_propietarioKeyPressed

    private void txt_propietarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_propietarioKeyReleased

    }//GEN-LAST:event_txt_propietarioKeyReleased

    private void txt_propietarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_propietarioKeyTyped

        //Cuenta la cantidad maxima de caracteres
        int numeroCaracteres = 29;
        if(txt_propietario.getText().length()> numeroCaracteres){
            evt.consume();
            JOptionPane.showMessageDialog(null,"Solo 30 caracteres.", "Validación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/advertencia.png", 32, 32));
        }

        //Forza a escribir en mayuscula
        char c=evt.getKeyChar();
        if(Character.isLowerCase(c)){
            evt.setKeyChar(Character.toUpperCase(c));

        }
    }//GEN-LAST:event_txt_propietarioKeyTyped

    private void txt_colorVehiculoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_colorVehiculoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_colorVehiculoFocusGained

    private void txt_colorVehiculoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_colorVehiculoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_colorVehiculoFocusLost

    private void txt_colorVehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_colorVehiculoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_colorVehiculoActionPerformed

    private void txt_colorVehiculoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_colorVehiculoKeyTyped
        //Cuenta la cantidad maxima de caracteres
        int numeroCaracteres = 29;
        if(txt_colorVehiculo.getText().length()> numeroCaracteres){
            evt.consume();
            JOptionPane.showMessageDialog(null,"Solo 30 caracteres.", "Validación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/advertencia.png", 32, 32));
        }

        //Forza a escribir en mayuscula
        char c=evt.getKeyChar();
        if(Character.isLowerCase(c)){
            evt.setKeyChar(Character.toUpperCase(c));

        }
    }//GEN-LAST:event_txt_colorVehiculoKeyTyped

    private void cmb_tarifaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_tarifaItemStateChanged

    }//GEN-LAST:event_cmb_tarifaItemStateChanged

    private void cmb_tarifaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmb_tarifaFocusGained
        btn_eliminar.setEnabled(false);
        btn_ingresar.setEnabled(true);
        btn_generarQR.setEnabled(false);
        btn_editar.setEnabled(false);
    }//GEN-LAST:event_cmb_tarifaFocusGained

    private void cmb_conveniosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_conveniosItemStateChanged
        
    }//GEN-LAST:event_cmb_conveniosItemStateChanged

    private void cmb_conveniosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmb_conveniosFocusGained
        btn_eliminar.setEnabled(false);
        btn_ingresar.setEnabled(true);
        btn_generarQR.setEnabled(false);
        btn_editar.setEnabled(false);
    }//GEN-LAST:event_cmb_conveniosFocusGained

    private void cmb_tipoIdentificacionBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tipoIdentificacionBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_tipoIdentificacionBusquedaActionPerformed

    private void txt_noIdentificacionBusquedaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_noIdentificacionBusquedaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noIdentificacionBusquedaFocusGained

    private void txt_noIdentificacionBusquedaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_noIdentificacionBusquedaFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noIdentificacionBusquedaFocusLost

    private void txt_noIdentificacionBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_noIdentificacionBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noIdentificacionBusquedaActionPerformed

    private void txt_noIdentificacionBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_noIdentificacionBusquedaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_noIdentificacionBusquedaKeyTyped

    private void txt_propietarioBusquedaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_propietarioBusquedaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_propietarioBusquedaFocusGained

    private void txt_propietarioBusquedaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_propietarioBusquedaKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_propietarioBusquedaKeyPressed

    private void txt_propietarioBusquedaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_propietarioBusquedaKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_propietarioBusquedaKeyReleased

    private void txt_propietarioBusquedaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_propietarioBusquedaKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_propietarioBusquedaKeyTyped

    private void txt_propietarioBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_propietarioBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_propietarioBusquedaActionPerformed

    private void cmb_parqueaderosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmb_parqueaderosFocusGained
        btn_eliminar.setEnabled(false);
        btn_ingresar.setEnabled(true);
        btn_generarQR.setEnabled(false);
        btn_editar.setEnabled(false);
    }//GEN-LAST:event_cmb_parqueaderosFocusGained

    private void check_estaVehiculoEnParqueaderoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_estaVehiculoEnParqueaderoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_check_estaVehiculoEnParqueaderoActionPerformed

    private void Table_listaBicisYOtrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_listaBicisYOtrosMouseClicked
        btn_editar.setEnabled(true);
        btn_eliminar.setEnabled(true);
        btn_generarQR.setEnabled(true);
    }//GEN-LAST:event_Table_listaBicisYOtrosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarBicisyOtros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarBicisyOtros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarBicisyOtros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarBicisyOtros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    //Esto cambia la apariencia de la app para que se acomode al Siste Operativo
                    UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                    new GestionarBicisyOtros().setVisible(true);
                }catch (ClassNotFoundException | InstantiationException | IllegalAccessException | UnsupportedLookAndFeelException ex) {
                    //Logger.getLogger(GestionarParqueaderos.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable Table_listaBicisYOtros;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_generarQR;
    public static javax.swing.JButton btn_generarReporteBicisyOtros;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JCheckBox check_estaVehiculoEnParqueadero;
    private javax.swing.JComboBox<String> cmb_convenios;
    private javax.swing.JComboBox<String> cmb_parqueaderos;
    private javax.swing.JComboBox<String> cmb_tarifa;
    private javax.swing.JComboBox<String> cmb_tipoIdentificacion;
    private javax.swing.JComboBox<String> cmb_tipoIdentificacionBusqueda;
    private javax.swing.JComboBox<String> cmb_tipoVehiculo;
    private javax.swing.JComboBox<String> cmb_tipoVehiculoBusqueda;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JTextField txt_colorVehiculo;
    private javax.swing.JTextField txt_noIdentificacion;
    private javax.swing.JTextField txt_noIdentificacionBusqueda;
    private javax.swing.JTextField txt_propietario;
    private javax.swing.JTextField txt_propietarioBusqueda;
    // End of variables declaration//GEN-END:variables
   
    //Metodo que limpia el formulario en caso de ingresar tablero principal
    public void Limpiar(){
        cmb_tipoIdentificacion.setSelectedIndex(0);
        txt_noIdentificacion.setText("");
        txt_propietario.setText("");
        cmb_tipoVehiculo.setSelectedIndex(0);
        txt_colorVehiculo.setText("");
        cmb_parqueaderos.setSelectedIndex(0);
        cmb_convenios.setSelectedIndex(0);
        cmb_tarifa.setSelectedIndex(0);
        check_estaVehiculoEnParqueadero.setSelected(false);
    }
    
    //Metodo que normaliza el formulario en caso tablero compartido
    public void Normalizar(){
        txt_noIdentificacion.setBackground(Color.WHITE);
        txt_propietario.setBackground(Color.WHITE);
        txt_colorVehiculo.setBackground(Color.WHITE);
        cmb_parqueaderos.setBackground(Color.WHITE);
        cmb_convenios.setBackground(Color.WHITE);
        cmb_tarifa.setBackground(Color.WHITE);
        check_estaVehiculoEnParqueadero.setBackground(Color.WHITE);;
    }
    
    //Metodo que se invoca al cerrar el jFrame
    private void cerrarGestorBibicletasYOtrosVehiculos(){
        
        String botones[] = {"Si", "No"};
        int eleccion = JOptionPane.showOptionDialog(this, "¿Está seguro que desea cerrar?", "Administrador de bicis y otros", 0, JOptionPane.QUESTION_MESSAGE, paramControla.getIcon("/icons/pregunta.png", 32, 32), botones, this);
        
        if(eleccion == JOptionPane.YES_OPTION){
            dispose();
            //Avisamos que esta ventana se encuentra cerrada 
            MenuAdministrador.hayAlgunaVentanaAbiertaDelSistema = false;
            PanelVehiculos.btn_gestorOtrosVehiculos.setEnabled(true);
        }
    }

    //Metodo que ejecuta loss hilos que traen los datos del estado de cupo de parqueadero, Convenios, tarifas y generacion de codiggo qr en tiempo real  
    @Override
    public void run() {
        Thread ct = Thread.currentThread();
        Thread ct1 = Thread.currentThread();
        Thread ct2 = Thread.currentThread();
        
        while(ct == hilo1){

            DefaultComboBoxModel modeloParq = new DefaultComboBoxModel(parq.mostrarParqueaderosTipoResidente("'BICICLETA', 'PATINETA', 'OTRO'"));
            cmb_parqueaderos.setModel(modeloParq);

            try{
                ct.sleep(30000);
            }catch(InterruptedException e){}
        }

        while(ct1 == hilo2){

            DefaultComboBoxModel modeloConv = new DefaultComboBoxModel(conv.mostrarConveniosDisponibles());
            cmb_convenios.setModel(modeloConv);
            conv.almacenarNombresConvenio();

            try{
                ct1.sleep(30000);
            }catch(InterruptedException e){}
        }

        while(ct2 == hilo3){

            DefaultComboBoxModel modeloTarif = new DefaultComboBoxModel(tarif.mostrarTarifasDisponibles());
            cmb_tarifa.setModel(modeloTarif);
            tarif.almacenarNombresTarifa();

            try{
                ct2.sleep(30000);
            }catch(InterruptedException e){}
        }
    }   
}


