package vista;

import modelo.Parqueadero;
import controlador.ConvenioControlador;
import controlador.FacturaControlador;
import controlador.ParametroControlador;
import controlador.ParqueaderoControlador;
import controlador.TarifaControlador;
import controlador.UsuarioControlador;
import controlador.VehiculoControlador;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.net.URL;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JScrollBar;
import javax.swing.table.DefaultTableModel;
import modelo.Convenio;
import modelo.Factura;
import modelo.Tarifa;
import modelo.Vehiculo;
import org.apache.log4j.Logger;




/**
 *
 * @author ALEJO
 */
public class PanelVehiculos extends javax.swing.JPanel implements Runnable{

    public static DefaultTableModel modelo;
    Parqueadero nomParqueadero;
    Convenio nomConvenio;
    Tarifa nomTarifa;
    int Fila;
    int FilaAnterior;
    public static String vehiculo_update;
    public static boolean hayVehiculoEnEdicion = false;
    String user = "";
    public static String placa;
    public static String dueño;
    public static String tipoVehiculo;
    
    VehiculoControlador vehicontrolador;
    Vehiculo nuevoVehiculo = new Vehiculo(0, "", "", "", "", "", "", "", 0, 0, 0);
    ParqueaderoControlador parqControla;
    TarifaControlador tarifaControla;
    ConvenioControlador convenioControla;
    FacturaControlador facturaControla;
    ParametroControlador paramControla = new ParametroControlador();
    UsuarioControlador usuarioControla;
    
    Factura nuevaFactura = new Factura(0, "", "", 0, "", "", "", "", "", 0, 0, "", "", 0, 0, "", 0, "", "", "", "", "", "");
    
    boolean elvehiculoTieneFacturaPrimerIngresoPrevRegistrada = true;
    
    //Declaramos los objetos  y se los aprovisionamos a su combobox
    Parqueadero parq = new Parqueadero();
    Convenio conv = new Convenio();
    Tarifa tarif = new Tarifa();
    
    //Variables boton editar
    String parqueaderoActual;
    String convenioActual;
    String tarifaActual;
    String placadelVehiculoAEditar;
    int idParqueaderoActual;
    int idConvenioActual;
    int idTarifaActual;
    Parqueadero parqueaderoEditar;
    Convenio convenioEditar;
    Tarifa tarifaEditar;
    
    Thread hilo1 = new Thread(this);
    Thread hilo2 = new Thread(this);
    Thread hilo3 = new Thread(this);
        
    private final Logger log = Logger.getLogger(PanelVehiculos.class);
    private URL url = PanelVehiculos.class.getResource("Log4j.properties");
    
    JScrollBar pane = new JScrollBar();
 
    /**
     * Creates new form PanelVehiculos
     */
    public PanelVehiculos() {
        initComponents();    
        user = Login.usuario;
        
        vehicontrolador = new VehiculoControlador();
        parqControla = new ParqueaderoControlador();
        convenioControla = new ConvenioControlador();
        tarifaControla = new TarifaControlador();
        facturaControla = new FacturaControlador();
        paramControla = new ParametroControlador();
        usuarioControla = new UsuarioControlador();
        
        hilo1.start();
        hilo2.start();
        hilo3.start();           
        vehicontrolador.cargarTablaDeVehiculosPorDefault();
        //Cargamos el proceso que se encarga de registrar el ticket qr de carros y motos
        vehicontrolador.cargarProcesoDeRegistroQRCarrosYMotos();
        
        //Agregamos la funcion de editar vehiculo al hacer click sobre el registro de la tabla
        Table_listaVehiculos.addMouseListener(new MouseAdapter() {
        @Override
        public void mouseClicked(MouseEvent e){
            int fila_point =  Table_listaVehiculos.rowAtPoint(e.getPoint());
            int columna_point = 0;

            if(fila_point > -1){
                vehiculo_update = (String) modelo.getValueAt(fila_point, columna_point);              
            }
        }
    });
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_estadoParqueadero = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_listaVehiculos = new javax.swing.JTable();
        btn_gestorOtrosVehiculos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_placa = new javax.swing.JTextField();
        txt_propietario = new javax.swing.JTextField();
        cmb_tipoVehiculo = new javax.swing.JComboBox<>();
        cmb_parqueaderos = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        cmb_convenios = new javax.swing.JComboBox<>();
        btn_ingresar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btn_eliminar = new javax.swing.JButton();
        cmb_tarifa = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_busquedapropietario = new javax.swing.JTextField();
        txt_busquedaPlaca = new javax.swing.JTextField();
        cmb_tipoVehiculoBusqueda = new javax.swing.JComboBox<>();
        btn_buscar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        btn_generarQR = new javax.swing.JButton();
        check_estaVehiculoEnParqueadero = new javax.swing.JCheckBox();
        btn_editar = new javax.swing.JButton();
        btn_generarReporteVehiculos = new javax.swing.JButton();

        btn_estadoParqueadero.setText("Estado de Parqueadero");
        btn_estadoParqueadero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_estadoParqueaderoActionPerformed(evt);
            }
        });

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Table_listaVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Placa", "Propietario", "Tipo", "N° Parq", "Convenio", "Tarifa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Table_listaVehiculos.setEditingColumn(0);
        Table_listaVehiculos.setEditingRow(0);
        Table_listaVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_listaVehiculosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_listaVehiculos);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 973, 197));

        btn_gestorOtrosVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bicicleta.png"))); // NOI18N
        btn_gestorOtrosVehiculos.setText("Bicicletas y otros");
        btn_gestorOtrosVehiculos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_gestorOtrosVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gestorOtrosVehiculosActionPerformed(evt);
            }
        });
        add(btn_gestorOtrosVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, -1, 43));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Placa:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Propietario:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("Tipo de vehiculo:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 20));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("N° de Parqueadero:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        txt_placa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_placaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_placaFocusLost(evt);
            }
        });
        txt_placa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_placaActionPerformed(evt);
            }
        });
        txt_placa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_placaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_placaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_placaKeyTyped(evt);
            }
        });
        add(txt_placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 81, -1));

        txt_propietario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txt_propietarioFocusGained(evt);
            }
        });
        txt_propietario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_propietarioKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_propietarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_propietarioKeyTyped(evt);
            }
        });
        add(txt_propietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 314, -1));

        cmb_tipoVehiculo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "AUTOMOVIL", "MOTO" }));
        cmb_tipoVehiculo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_tipoVehiculoItemStateChanged(evt);
            }
        });
        cmb_tipoVehiculo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmb_tipoVehiculoFocusGained(evt);
            }
        });
        add(cmb_tipoVehiculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, -1, -1));

        cmb_parqueaderos.setAutoscrolls(true);
        cmb_parqueaderos.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmb_parqueaderosFocusGained(evt);
            }
        });
        add(cmb_parqueaderos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 271, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Convenio:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, -1, -1));

        cmb_convenios.setAutoscrolls(true);
        cmb_convenios.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_conveniosItemStateChanged(evt);
            }
        });
        cmb_convenios.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmb_conveniosFocusGained(evt);
            }
        });
        add(cmb_convenios, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 271, -1));

        btn_ingresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Save_icon-icons.com_73702.png"))); // NOI18N
        btn_ingresar.setText("Guardar");
        btn_ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });
        add(btn_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 0, -1, 40));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 197, 1100, 7));

        btn_eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ic_delete_128_28267.png"))); // NOI18N
        btn_eliminar.setText("Eliminar");
        btn_eliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_eliminar.setEnabled(false);
        btn_eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_eliminarActionPerformed(evt);
            }
        });
        add(btn_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        cmb_tarifa.setAutoscrolls(true);
        cmb_tarifa.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_tarifaItemStateChanged(evt);
            }
        });
        cmb_tarifa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmb_tarifaFocusGained(evt);
            }
        });
        add(cmb_tarifa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 272, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Tarifa:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Buscar por"));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Placa:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("Propietario:");

        txt_busquedapropietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_busquedapropietarioActionPerformed(evt);
            }
        });
        txt_busquedapropietario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_busquedapropietarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_busquedapropietarioKeyTyped(evt);
            }
        });

        txt_busquedaPlaca.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_busquedaPlacaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_busquedaPlacaKeyTyped(evt);
            }
        });

        cmb_tipoVehiculoBusqueda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "AUTOMOVIL", "MOTO" }));
        cmb_tipoVehiculoBusqueda.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmb_tipoVehiculoBusquedaItemStateChanged(evt);
            }
        });
        cmb_tipoVehiculoBusqueda.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmb_tipoVehiculoBusquedaFocusGained(evt);
            }
        });
        cmb_tipoVehiculoBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tipoVehiculoBusquedaActionPerformed(evt);
            }
        });

        btn_buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel9.setText("Tipo de vehiculo:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_busquedaPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txt_busquedapropietario)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cmb_tipoVehiculoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                        .addComponent(btn_buscar)))
                .addGap(6, 6, 6))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel7)
                    .addComponent(txt_busquedaPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel8))
                    .addComponent(txt_busquedapropietario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_tipoVehiculoBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 400, 140));

        btn_generarQR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/qr.png"))); // NOI18N
        btn_generarQR.setText("QR");
        btn_generarQR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_generarQR.setEnabled(false);
        btn_generarQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarQRActionPerformed(evt);
            }
        });
        add(btn_generarQR, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, -1, -1));

        check_estaVehiculoEnParqueadero.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        check_estaVehiculoEnParqueadero.setText("Está en parqueadero");
        check_estaVehiculoEnParqueadero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_estaVehiculoEnParqueaderoActionPerformed(evt);
            }
        });
        add(check_estaVehiculoEnParqueadero, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, -1, -1));

        btn_editar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit-validated_40458.png"))); // NOI18N
        btn_editar.setText("Editar");
        btn_editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_editar.setEnabled(false);
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });
        add(btn_editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 110, -1));

        btn_generarReporteVehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/generarPDF.png"))); // NOI18N
        btn_generarReporteVehiculos.setText("Generar Informe PDF");
        btn_generarReporteVehiculos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_generarReporteVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generarReporteVehiculosActionPerformed(evt);
            }
        });
        add(btn_generarReporteVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 420, -1, 43));
    }// </editor-fold>//GEN-END:initComponents

    private void btn_estadoParqueaderoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_estadoParqueaderoActionPerformed
       
    }//GEN-LAST:event_btn_estadoParqueaderoActionPerformed

    //Metodo que abre la ventana que permite gestionar las bicicletas y otros vehiculos
    private void btn_gestorOtrosVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gestorOtrosVehiculosActionPerformed
        MenuAdministrador.hayAlgunaVentanaAbiertaDelSistema = true;
        new GestionarBicisyOtros().setVisible(true);
        btn_gestorOtrosVehiculos.setEnabled(false);
    }//GEN-LAST:event_btn_gestorOtrosVehiculosActionPerformed

    
    private void txt_placaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_placaKeyTyped
        
        //Cuenta la cantidad maxima de caracteres
        int numeroCaracteres = 5;
        if(txt_placa.getText().length()> numeroCaracteres){
            evt.consume();
            JOptionPane.showMessageDialog(null,"Solo 6 caracteres.", "Validación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/advertencia.png", 32, 32));
        }
        
        //Forza a escribir en mayuscula
        char c=evt.getKeyChar();
        if(Character.isLowerCase(c)){
            evt.setKeyChar(Character.toUpperCase(c));
            
        }
    }//GEN-LAST:event_txt_placaKeyTyped

    private void txt_propietarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_propietarioKeyTyped
        
        //Cuenta la cantidad maxima de caracteres
        int numeroCaracteres = 29;
        if(txt_propietario.getText().length()> numeroCaracteres){
            evt.consume();
            JOptionPane.showMessageDialog(null,"Solo 30 caracteres.", "Validación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/advertencia.png", 32, 32));
        }

        //Forza a escribir en mayuscula
        char c=evt.getKeyChar();
        if(Character.isLowerCase(c)){
            evt.setKeyChar(Character.toUpperCase(c));
            
        }
    }//GEN-LAST:event_txt_propietarioKeyTyped

    //Metodo del boton ingresar
    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        
        int clase_cmb, parqueadero_cmb, validacion = 0;
        String qrInfo = "";
        Parqueadero parqSeleccionado = new Parqueadero();
                        
        placa = txt_placa.getText().trim();
        dueño = txt_propietario.getText().trim();
        clase_cmb = cmb_tipoVehiculo.getSelectedIndex();
        parqueadero_cmb = cmb_parqueaderos.getSelectedIndex();
        
        Convenio convSeleccionado = new Convenio();
        Tarifa tarifSeleccionada = new Tarifa();     
        
        convSeleccionado = (Convenio)cmb_convenios.getSelectedItem();
        tarifSeleccionada = (Tarifa)cmb_tarifa.getSelectedItem();
        
        boolean vehiculoEnParqueadero = check_estaVehiculoEnParqueadero.isSelected();
        String vehiculoEstaEnParqueo = "";
        
        //Capturamos el objeto parqueadero para validar le verdadero id en base de datos
        parqSeleccionado = (Parqueadero)cmb_parqueaderos.getSelectedItem();
                       
        int minimoCaracteres = 6;
        
        if(placa.equals("")){
            txt_placa.setBackground(Color.red);
            validacion++;
        }
        if(dueño.equals("")){
            txt_propietario.setBackground(Color.red);
            validacion++;
        }
        
        if(clase_cmb == 0){
            tipoVehiculo = "Seleccione";
            cmb_tipoVehiculo.setBackground(Color.red);
            validacion++;
        }        
        else if(clase_cmb == 1){
            tipoVehiculo = "AUTOMOVIL";
        }else if(clase_cmb == 2){
            tipoVehiculo = "MOTO";
        }
        
        if(parqueadero_cmb==0){
            cmb_parqueaderos.setBackground(Color.red);
            validacion++;
        }
                      
        if(txt_placa.getText().length() < minimoCaracteres){
            txt_placa.setBackground(Color.red);
            JOptionPane.showMessageDialog(null,"Placa no válida.", "Validación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/advertencia.png", 32, 32));
            txt_placa.setText("");
            validacion++;
        }
        
        if(hayVehiculoEnEdicion == true){
            JOptionPane.showMessageDialog(null, "No Permitido, cierre la ventana de edición de vehiculos para continuar.", "Validación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/advertencia.png", 32, 32));
            txt_placa.requestFocus();
            validacion++;
        }
        
        if(vehiculoEnParqueadero){
            vehiculoEstaEnParqueo = "Si";
        }else{
            vehiculoEstaEnParqueo = "No";
        }
                
        int vehiculoYaPreviamenteRegistrado = vehicontrolador.evaluarExistenciaDelVehiculo(null, placa, null, null);
        
        if(vehiculoYaPreviamenteRegistrado == 1){
            JOptionPane.showMessageDialog(null, "El vehiculo ya se encuentra registrado.", "Validación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/advertencia.png", 32, 32));
            txt_placa.setText("");
            validacion++;
        }      
        
        //Validamos el verdadero id del parqueadero en bd
        int idRealDelParqueaderoSeleccionado = parqControla.consultarIdParqueadero(parqSeleccionado.getNombre());
                
        boolean parqueaderoEstaOcupado = parqControla.consultarDisponibilidadDeParqueaderoMedianteID(idRealDelParqueaderoSeleccionado);
        
        if(parqueaderoEstaOcupado == true){
            JOptionPane.showMessageDialog(null, "El parqueadero indicado ya se encuentra ocupado.", "Validación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/advertencia.png", 32, 32));
            cmb_parqueaderos.setSelectedIndex(0);
            validacion++;
        }else{
            boolean parqueaderoEsCompatible = parqControla.consultarCompatibilidadDeParqueaderoMedianteID(idRealDelParqueaderoSeleccionado, tipoVehiculo);
            if(!parqueaderoEsCompatible){
               JOptionPane.showMessageDialog(null, "El parqueadero indicado no es compatible con el vehiculo.", "Validación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/advertencia.png", 32, 32));
               cmb_parqueaderos.setSelectedIndex(0);
               validacion++;  
            }
        } 
               
         //Validamos el verdadero id del convenio y de la tarifa en bd
        int idRealDelConvenioSeleccionado = convenioControla.consultarIdDeunConvenio(convSeleccionado.getNombre());
        int idRealDeTarifaSeleccionada = tarifaControla.consultarIdDeunaTarifa(tarifSeleccionada.getNombreTarifa());
             
        if(validacion == 0 ){
            //Reanudamos el proceso de generacion ticket qr carros y motos
            vehicontrolador.reanudarProcesoDeRegistroQRCarrosYMotos();
            
            //Encapsulamos el objeto vehiculo 
            nuevoVehiculo.setId(0);
            qrInfo = placa+paramControla.generarConsecutivo(10);
            nuevoVehiculo.setQr_consecutivo(qrInfo);
            nuevoVehiculo.setPlaca(placa);
            nuevoVehiculo.setPropietario(dueño);
            nuevoVehiculo.setTipoVehiculo(tipoVehiculo);
            nuevoVehiculo.setId_parqueadero(idRealDelParqueaderoSeleccionado);
            nuevoVehiculo.setId_convenio(idRealDelConvenioSeleccionado);
            nuevoVehiculo.setId_tarifa(idRealDeTarifaSeleccionada); 
            nuevoVehiculo.setEstaEnParqueadero(vehiculoEstaEnParqueo);
            
            //Registramos el vehiculo
            vehicontrolador.crearVehiculo(nuevoVehiculo);
            
            //Obtenemos el id con el que se registro el vehiculo
            int idDelVehiculo = vehicontrolador.consultarIdDeUnVehiculo(placa, null, null);
            
            //Evaluamos si el vehiculo tiene factura abierta
            int vehiculoConFctraAbierta = vehicontrolador.consultarSiVehiculoTieneFacturasAbiertas(idDelVehiculo,null,null,null);
            
            //Generamos el ingreso del vehiculo en caja dependiendo de si esta o no en parqueadero
            if(vehiculoEstaEnParqueo.equals("Si")){
                if(vehiculoConFctraAbierta == 1){
                    int idFctra = facturaControla.consultarIdDeUnaFacturaAbierta(placa, null, null);                    
                    facturaControla.actualizarFacturaAbierta(idFctra, idDelVehiculo, "", "", "", "", "", 0, 0, 0);
                    
                    //Validamos si el parqueadero utilizado por el vehiculo antes de registrarse en el sistema es igual al ingresado por caja
                    int idDelParqDelVehiculoAntesDeSerRegistrado = vehicontrolador.consultarIdParqQueOcupaUnVehiculo(placa, null, null);
                    
                    if(idDelParqDelVehiculoAntesDeSerRegistrado != idRealDelParqueaderoSeleccionado){
                       parqControla.liberarParqueadero(tipoVehiculo, placa, null, null);
                       parqControla.actualizarEstadoDeParqueadero(tipoVehiculo, placa, null, null, dueño, idRealDelParqueaderoSeleccionado, vehiculoEstaEnParqueo);
                    }
                    
                }else{
                    //Modelamos la factura de primer ingreso 
                    nuevaFactura.setId(0);
                    nuevaFactura.setCodigo("FAC" + paramControla.generarConsecutivo(10));
                    nuevaFactura.setFechaDeFactura(facturaControla.fecha_de_factura());
                    nuevaFactura.setIdDelVehiculo(idDelVehiculo);
                    nuevaFactura.setFacturadoPor(usuarioControla.consultarIdDeunUsuario(user));
                    nuevaFactura.setEstadoDeFactura("Abierta");
                    nuevaFactura.setEstaContabilizada("No");
                    nuevaFactura.setFechaDeIngresoVehiculo("1990-01-01 23:59:00"); //No generará cobro pues no estamos teniendo en cuenta la hora en que fue ingresado
                    nuevaFactura.setId_cierre(1);

                    //Creamos el objeto Factura de primer ingreso
                    facturaControla.crearFactura(nuevaFactura, true);
                    
                    //Actualizamos el estado del parqueadero
                    parqControla.actualizarEstadoDeParqueadero(tipoVehiculo, placa, null, null, dueño, idRealDelParqueaderoSeleccionado, vehiculoEstaEnParqueo);
                }
                                
            }else{
                if(vehiculoConFctraAbierta == 1){
                    
                    int idFctra = facturaControla.consultarIdDeUnaFacturaAbierta(placa, null, null);
                    facturaControla.actualizarFacturaAbierta(idFctra, idDelVehiculo, "", "", "", "", "", 0, 0, 0);
                    
                    //Validamos si el parqueadero utilizado por el vehiculo antes de registrarse en el sistema es igual al ingresado por caja
                    int idDelParqDelVehiculoAntesDeSerRegistrado = vehicontrolador.consultarIdParqQueOcupaUnVehiculo(placa, null, null);
                    
                    if(idDelParqDelVehiculoAntesDeSerRegistrado != idRealDelParqueaderoSeleccionado){
                       parqControla.liberarParqueadero(tipoVehiculo, placa, null, null);
                       vehiculoEstaEnParqueo = "Si";
                       parqControla.actualizarEstadoDeParqueadero(tipoVehiculo, placa, null, null, dueño, idRealDelParqueaderoSeleccionado, vehiculoEstaEnParqueo);
                    }
                
                }else{    
                    parqControla.actualizarEstadoDeParqueadero(tipoVehiculo, placa, null, null, dueño, idRealDelParqueaderoSeleccionado, vehiculoEstaEnParqueo);
                }    
            }    
            
            //Agregamos el objeto vehiculo a la tabla de vehiculos
            Object[] fila = new Object[6];
            fila[0] = placa;
            fila[1] = dueño;
            fila[2] = tipoVehiculo;
            fila[3] = parqSeleccionado.getNombre();
            fila[4] = convSeleccionado.getNombre();
            fila[5] = tarifSeleccionada.getNombreTarifa();
            modelo.addRow(fila);
            
            JOptionPane.showMessageDialog(null, "Vehiculo registrado satisfactoriamente.", "Confirmación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/exitoso.png", 32, 32));
            //Generamos el codigo QR del vehiculo y lo imprimimos
            vehicontrolador.generarQR(placa+" - "+dueño, qrInfo, tipoVehiculo);
            Limpiar();
            Normalizar();
            
        }else{
            JOptionPane.showMessageDialog(null, "Debes de llenar todos los campos.", "Validación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/advertencia.png", 32, 32));
            Normalizar();
        } 
    }//GEN-LAST:event_btn_ingresarActionPerformed

    //Metodo del boton Eliminar
    private void btn_eliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_eliminarActionPerformed
          
        Fila = Table_listaVehiculos.getSelectedRow();
        int cantidadFilas = Table_listaVehiculos.getSelectedRowCount();
         
        if(cantidadFilas == 0){
            JOptionPane.showMessageDialog(null, "Seleccione el vehiculo que desea eliminar.", "Validación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/advertencia.png", 32, 32));
        }else{    
            String placa = Table_listaVehiculos.getValueAt(Fila, 0).toString();
            String propietario = Table_listaVehiculos.getValueAt(Fila, 1).toString();
            int idDelVehiculo = vehicontrolador.consultarIdDeUnVehiculo(placa, null, null);
            tipoVehiculo = Table_listaVehiculos.getValueAt(Fila, 2).toString();
            String botones[] = {"Si", "No"};
            int decision = JOptionPane.showOptionDialog(this, "¿Está seguro que desea eliminar?", "Eliminar vehiculo", 0, JOptionPane.QUESTION_MESSAGE, paramControla.getIcon("/icons/pregunta.png", 32, 32), botones, this);
            
            if(decision == JOptionPane.YES_OPTION){               
                
                vehicontrolador.eliminarVehiculo(idDelVehiculo);
                int elvehiculoTieneFacturaAbierta = vehicontrolador.consultarSiVehiculoTieneFacturasAbiertas(idDelVehiculo,placa,null,null);

                if(elvehiculoTieneFacturaAbierta == 1){
                    facturaControla.eliminarFacturaAbierta(idDelVehiculo,null, null, null);
                } 

                JOptionPane.showMessageDialog(null, "El vehiculo ha sido eliminado", "Confirmación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/exitoso.png", 32, 32)); 
                //Eliminamos el codigo qr del vehiculo
                vehicontrolador.eliminarQr(placa+" - "+propietario, tipoVehiculo);
                modelo.removeRow(Fila);
                parqControla.liberarParqueadero(tipoVehiculo, placa, null, null);
                Limpiar();                              
                
            }else if(decision == JOptionPane.NO_OPTION){
                btn_ingresar.setEnabled(true);
            }
        }
    }//GEN-LAST:event_btn_eliminarActionPerformed

    
    private void Table_listaVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_listaVehiculosMouseClicked
        btn_editar.setEnabled(true);
        btn_eliminar.setEnabled(true);
        btn_generarQR.setEnabled(true);
    }//GEN-LAST:event_Table_listaVehiculosMouseClicked

    
    private void txt_placaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_placaKeyReleased
        
    }//GEN-LAST:event_txt_placaKeyReleased
    
    private void txt_propietarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_propietarioKeyReleased
        
    }//GEN-LAST:event_txt_propietarioKeyReleased

    
    private void cmb_conveniosItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_conveniosItemStateChanged
        int conv_string = cmb_convenios.getSelectedIndex();
        String tipVehi_string = (String)cmb_tipoVehiculo.getSelectedItem();
        
        if(conv_string == 1){
            if(tipVehi_string.equals("AUTOMOVIL")){
            cmb_tarifa.setSelectedIndex(2);

            } else if(tipVehi_string.equals("MOTO")){
                cmb_tarifa.setSelectedIndex(3);
            }
        }
        
        if(conv_string > 1){
            cmb_tarifa.setSelectedIndex(1);
        } 
       
    }//GEN-LAST:event_cmb_conveniosItemStateChanged

    private void txt_busquedaPlacaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_busquedaPlacaKeyReleased
       
    }//GEN-LAST:event_txt_busquedaPlacaKeyReleased

    private void txt_busquedaPlacaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_busquedaPlacaKeyTyped
        //Cuenta la cantidad maxima de caracteres
        int numeroCaracteres = 5;
        if(txt_placa.getText().length()> numeroCaracteres){
            evt.consume();
            JOptionPane.showMessageDialog(null,"Solo 6 caracteres.", "Validación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/advertencia.png", 32, 32));
        }
        
        //Forza a escribir en mayuscula
        char c=evt.getKeyChar();
        if(Character.isLowerCase(c)){
            evt.setKeyChar(Character.toUpperCase(c));
            
        }
    }//GEN-LAST:event_txt_busquedaPlacaKeyTyped

    private void txt_busquedapropietarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_busquedapropietarioKeyReleased
       
    }//GEN-LAST:event_txt_busquedapropietarioKeyReleased

    private void txt_busquedapropietarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_busquedapropietarioKeyTyped
        //Forza a escribir en mayuscula
        char c=evt.getKeyChar();
        if(Character.isLowerCase(c)){
            evt.setKeyChar(Character.toUpperCase(c));
        }
        
        //Cuenta la cantidad maxima de caracteres
        int numeroCaracteres = 30;
        if(txt_placa.getText().length()> numeroCaracteres){
            evt.consume();
            JOptionPane.showMessageDialog(null,"Solo 30 caracteres.", "Validación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/advertencia.png", 32, 32));
        }
    }//GEN-LAST:event_txt_busquedapropietarioKeyTyped

    private void txt_placaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_placaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_placaActionPerformed

    private void txt_placaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_placaKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            Limpiar();  
            btn_editar.setEnabled(false);
            btn_eliminar.setEnabled(false);
            btn_ingresar.setEnabled(true);
            btn_generarQR.setEnabled(false);
        }
    }//GEN-LAST:event_txt_placaKeyPressed

    private void txt_propietarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_propietarioKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            Limpiar(); 
            btn_eliminar.setEnabled(false);
            btn_ingresar.setEnabled(true);
            btn_generarQR.setEnabled(false);
        }
    }//GEN-LAST:event_txt_propietarioKeyPressed

    private void cmb_tarifaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_tarifaItemStateChanged

    }//GEN-LAST:event_cmb_tarifaItemStateChanged

    //Metodo del boton Eliminar
    private void btn_generarQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarQRActionPerformed
        Fila = Table_listaVehiculos.getSelectedRow();
        int cantidadFilas = Table_listaVehiculos.getSelectedRowCount();
         
        if(cantidadFilas == 0){
            JOptionPane.showMessageDialog(null, "Seleccione el vehiculo al que desea generar su codigo qr.", "Validación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/advertencia.png", 32, 32));
        }else{
            placa = Table_listaVehiculos.getValueAt(Fila, 0).toString();
            dueño = Table_listaVehiculos.getValueAt(Fila, 1).toString();
            tipoVehiculo = Table_listaVehiculos.getValueAt(Fila, 2).toString();
            vehicontrolador.generarTicketQrVehiculo(placa+" - "+dueño, false, "", tipoVehiculo);
            JOptionPane.showMessageDialog(null, "Codigo qr generado satisfactoriamente.", "Confirmación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/exitoso.png", 32, 32));
        }
    }//GEN-LAST:event_btn_generarQRActionPerformed

    private void txt_placaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_placaFocusGained
        btn_eliminar.setEnabled(false);
        btn_ingresar.setEnabled(true);
        btn_generarQR.setEnabled(false);  
        btn_editar.setEnabled(false);
    }//GEN-LAST:event_txt_placaFocusGained

    private void txt_propietarioFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_propietarioFocusGained
        btn_eliminar.setEnabled(false);
        btn_ingresar.setEnabled(true);
        btn_generarQR.setEnabled(false);
        btn_editar.setEnabled(false);
    }//GEN-LAST:event_txt_propietarioFocusGained

    private void cmb_tipoVehiculoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmb_tipoVehiculoFocusGained
        btn_eliminar.setEnabled(false);
        btn_ingresar.setEnabled(true);
        btn_generarQR.setEnabled(false);
        btn_editar.setEnabled(false);
    }//GEN-LAST:event_cmb_tipoVehiculoFocusGained

    private void cmb_parqueaderosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmb_parqueaderosFocusGained
        btn_eliminar.setEnabled(false);
        btn_ingresar.setEnabled(true);
        btn_generarQR.setEnabled(false);
        btn_editar.setEnabled(false);
    }//GEN-LAST:event_cmb_parqueaderosFocusGained

    private void cmb_conveniosFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmb_conveniosFocusGained
        btn_eliminar.setEnabled(false);
        btn_ingresar.setEnabled(true);
        btn_generarQR.setEnabled(false);
        btn_editar.setEnabled(false);
    }//GEN-LAST:event_cmb_conveniosFocusGained

    private void cmb_tarifaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmb_tarifaFocusGained
        btn_eliminar.setEnabled(false);
        btn_ingresar.setEnabled(true);
        btn_generarQR.setEnabled(false);
        btn_editar.setEnabled(false);
    }//GEN-LAST:event_cmb_tarifaFocusGained

    private void cmb_tipoVehiculoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_tipoVehiculoItemStateChanged
       
    }//GEN-LAST:event_cmb_tipoVehiculoItemStateChanged

    private void check_estaVehiculoEnParqueaderoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_estaVehiculoEnParqueaderoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_check_estaVehiculoEnParqueaderoActionPerformed

    private void txt_placaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_placaFocusLost
      
    }//GEN-LAST:event_txt_placaFocusLost

    //Metodo del boton Editar
    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
        Fila = Table_listaVehiculos.getSelectedRow();
        int cantidadFilas = Table_listaVehiculos.getSelectedRowCount();
         
        if(cantidadFilas == 0){
            JOptionPane.showMessageDialog(null, "Seleccione el vehiculo que desea editar.", "Validación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/advertencia.png", 32, 32));
        }else{    
            
            if(hayVehiculoEnEdicion == true){
                JOptionPane.showMessageDialog(null, "No Permitido.", "Error", JOptionPane.INFORMATION_MESSAGE, new ImageIcon("src/icons/Cancelar.png"));
            }else{
                hayVehiculoEnEdicion = true;
                vehiculo_update = Table_listaVehiculos.getValueAt(Fila, 0).toString();
                new EditarVehiculo().setVisible(true);
            }
        }
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_generarReporteVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generarReporteVehiculosActionPerformed
        String sentenciaSQLParaReporte = " AND vehiculos.TipoVehiculo IN ('AUTOMOVIL', 'MOTO')";
        String placa = txt_busquedaPlaca.getText();
        String propietario = txt_busquedapropietario.getText();
        int tipoVehiculo_cmb = cmb_tipoVehiculoBusqueda.getSelectedIndex();
        String tipoVehiculo_str = (String) cmb_tipoVehiculoBusqueda.getSelectedItem();
        

        //Validamos que ningun campo haya quedado en blanco y que al menos uno haya sido diligenciado
        if(placa.equals("") && propietario.equals("") && tipoVehiculo_cmb == 0){
            vehicontrolador.generarReportePDFdeCarrosYMotosRegistradas(sentenciaSQLParaReporte);
            btn_generarReporteVehiculos.setEnabled(false);

        }else{
            if(!placa.equals("")){
                //Agregamos la placa del vehiculo a la sentencia sql
                sentenciaSQLParaReporte = sentenciaSQLParaReporte + " AND vehiculos.Placa LIKE '%"+placa+"%'";
            }
            
            if(!propietario.equals("")){
                //Agregamos propietario del vehiculo a la sentencia sql
                sentenciaSQLParaReporte = sentenciaSQLParaReporte + " AND vehiculos.Propietario LIKE '%"+propietario+"%'";
            }

            if(tipoVehiculo_cmb != 0){
                //Agregamos tipo de vehiculo a la sentencia sql
                sentenciaSQLParaReporte= sentenciaSQLParaReporte + " AND vehiculos.TipoVehiculo = '"+tipoVehiculo_str+"'";
            }

            //Ejecutamos la sentencia SQL construida
            vehicontrolador.generarReportePDFdeCarrosYMotosRegistradas(sentenciaSQLParaReporte);
            btn_generarReporteVehiculos.setEnabled(false);
            
        }
    }//GEN-LAST:event_btn_generarReporteVehiculosActionPerformed

    private void txt_busquedapropietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_busquedapropietarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_busquedapropietarioActionPerformed

    private void cmb_tipoVehiculoBusquedaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmb_tipoVehiculoBusquedaItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_tipoVehiculoBusquedaItemStateChanged

    private void cmb_tipoVehiculoBusquedaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmb_tipoVehiculoBusquedaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_tipoVehiculoBusquedaFocusGained

    private void cmb_tipoVehiculoBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tipoVehiculoBusquedaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_tipoVehiculoBusquedaActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed

        String sentenciaSQL = "SELECT Ve.Placa, Ve.Propietario, Ve.TipoVehiculo, Parq.Nombre_parqueadero, Conv.Nombre_convenio, Tar.Nombre_tarifa FROM vehiculos Ve INNER JOIN parqueaderos Parq ON Ve.Id_parqueadero = Parq.Id_parqueadero INNER JOIN convenios Conv ON Ve.Id_convenio = Conv.Id_convenio INNER JOIN tarifas Tar ON Ve.Id_tarifa = Tar.Id_tarifa WHERE 1=1";
        String placa = txt_busquedaPlaca.getText();
        String propietario = txt_busquedapropietario.getText();
        int tipoVehiculo_cmb = cmb_tipoVehiculoBusqueda.getSelectedIndex();
        String tipoVehiculo_str = (String) cmb_tipoVehiculoBusqueda.getSelectedItem();
        

        //Validamos que ningun campo haya quedado en blanco y que al menos uno haya sido diligenciado
        if(placa.equals("") && propietario.equals("") && tipoVehiculo_cmb == 0){
            JOptionPane.showMessageDialog(null,"Debe diligenciar por lo menos un criterio de busqueda.", "Validación", JOptionPane.INFORMATION_MESSAGE, paramControla.getIcon("/icons/advertencia.png", 32, 32));
            vehicontrolador.cargarTablaDeVehiculosPorDefault();

        }else{
            if(!placa.equals("")){
                //Agregamos la placa del vehiculo a la sentencia sql
                sentenciaSQL = sentenciaSQL + " AND Ve.Placa LIKE '%"+placa+"%'";
            }
            
            if(!propietario.equals("")){
                //Agregamos propietario del vehiculo a la sentencia sql
                sentenciaSQL = sentenciaSQL + " AND Ve.Propietario LIKE '%"+propietario+"%'";
            }

            if(tipoVehiculo_cmb != 0){
                //Agregamos tipo de vehiculo a la sentencia sql
                sentenciaSQL = sentenciaSQL + " AND Ve.TipoVehiculo = '"+tipoVehiculo_str+"'";
            }

            //Ejecutamos la sentencia SQL construida
            vehicontrolador.buscarCarrosYMotos(sentenciaSQL);

        }
    }//GEN-LAST:event_btn_buscarActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable Table_listaVehiculos;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_eliminar;
    private javax.swing.JButton btn_estadoParqueadero;
    private javax.swing.JButton btn_generarQR;
    public static javax.swing.JButton btn_generarReporteVehiculos;
    public static javax.swing.JButton btn_gestorOtrosVehiculos;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JCheckBox check_estaVehiculoEnParqueadero;
    private javax.swing.JComboBox<String> cmb_convenios;
    private javax.swing.JComboBox<String> cmb_parqueaderos;
    private javax.swing.JComboBox<String> cmb_tarifa;
    private javax.swing.JComboBox<String> cmb_tipoVehiculo;
    private javax.swing.JComboBox<String> cmb_tipoVehiculoBusqueda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txt_busquedaPlaca;
    private javax.swing.JTextField txt_busquedapropietario;
    private javax.swing.JTextField txt_placa;
    private javax.swing.JTextField txt_propietario;
    // End of variables declaration//GEN-END:variables
    
    public void Limpiar(){
        txt_placa.setText("");
        txt_propietario.setText("");
        cmb_tipoVehiculo.setSelectedIndex(0);
        cmb_parqueaderos.setSelectedIndex(0);
        cmb_convenios.setSelectedIndex(0);
        cmb_tarifa.setSelectedIndex(0);
        check_estaVehiculoEnParqueadero.setSelected(false);
    } 
        
    public void Normalizar(){
        txt_placa.setBackground(Color.WHITE);
        txt_propietario.setBackground(Color.WHITE);
        cmb_tipoVehiculo.setBackground(Color.WHITE);
        cmb_parqueaderos.setBackground(Color.WHITE);
        cmb_convenios.setBackground(Color.WHITE);
        cmb_tarifa.setBackground(Color.WHITE);
        check_estaVehiculoEnParqueadero.setBackground(Color.WHITE);
    }
    
    //Metodo que ejecuta loss hilos que traen los datos del estado de cupo de parqueadero, Convenios, tarifas y generacion de codiggo qr en tiempo real    
    @Override
    public void run() {
        Thread ct = Thread.currentThread();
        Thread ct1 = Thread.currentThread();
        Thread ct2 = Thread.currentThread();
        
        while(ct == hilo1){

            DefaultComboBoxModel modeloParq = new DefaultComboBoxModel(parq.mostrarParqueaderosTipoResidente("'AUTOMOVIL','MOTO'"));
            cmb_parqueaderos.setModel(modeloParq);

            try{
                ct.sleep(30000);
            }catch(InterruptedException e){}
        }

        while(ct1 == hilo2){

            DefaultComboBoxModel modeloConv = new DefaultComboBoxModel(conv.mostrarConveniosDisponibles());
            cmb_convenios.setModel(modeloConv);
            conv.almacenarNombresConvenio();

            try{
                ct1.sleep(30000);
            }catch(InterruptedException e){}
        }

        while(ct2 == hilo3){

            DefaultComboBoxModel modeloTarif = new DefaultComboBoxModel(tarif.mostrarTarifasDisponibles());
            cmb_tarifa.setModel(modeloTarif);
            tarif.almacenarNombresTarifa();

            try{
                ct2.sleep(30000);
            }catch(InterruptedException e){}
        }
    }       
}







