package vista;

import java.net.URL;
import org.apache.log4j.Logger;

/**
 *
 * @author ALEJO
 */
public class PanelReportes extends javax.swing.JPanel {

    private final Logger log = Logger.getLogger(PanelReportes.class);
    private URL url = PanelReportes.class.getResource("Log4j.properties");
    
    /**
     * Creates new form PanelCorreo
     */
    public PanelReportes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_recaudo = new javax.swing.JButton();
        btn_tarifas = new javax.swing.JButton();

        btn_recaudo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/money.png"))); // NOI18N
        btn_recaudo.setText("Recaudo");
        btn_recaudo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_recaudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_recaudoActionPerformed(evt);
            }
        });

        btn_tarifas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Bill.png"))); // NOI18N
        btn_tarifas.setText("Facturas");
        btn_tarifas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_tarifas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tarifasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(129, 129, 129)
                .addComponent(btn_recaudo, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btn_tarifas, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(154, 154, 154))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_recaudo, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_tarifas, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    //Metodo boton Convenios
    private void btn_recaudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_recaudoActionPerformed
        new GestionarCierres().setVisible(true);
    }//GEN-LAST:event_btn_recaudoActionPerformed

    //Metodo del boton Tarifas
    private void btn_tarifasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tarifasActionPerformed
        new GestionarFacturas().setVisible(true);    
    }//GEN-LAST:event_btn_tarifasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_recaudo;
    public static javax.swing.JButton btn_tarifas;
    // End of variables declaration//GEN-END:variables
}
